<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 Statistics Review | Design of Experiments for Modeling and Simulation</title>
  <meta name="description" content="3 Statistics Review | Design of Experiments for Modeling and Simulation" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="3 Statistics Review | Design of Experiments for Modeling and Simulation" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Statistics Review | Design of Experiments for Modeling and Simulation" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introduction-to-r.html"/>
<link rel="next" href="analysis-of-variance-anova.html"/>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.17/datatables.js"></script>
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet" />
<script src="libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet" />
<script src="libs/selectize-0.12.0/selectize.min.js"></script>
<script src="libs/plotly-binding-4.9.3/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="https://doe.dscoe.org/">DoE for M&S</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction to DOE for M&amp;S</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#background."><i class="fa fa-check"></i><b>1.1</b> Background.</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#mission."><i class="fa fa-check"></i><b>1.2</b> Mission.</a><ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#simulation-analysis."><i class="fa fa-check"></i><b>1.2.1</b> Simulation Analysis.</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#enduring-resource."><i class="fa fa-check"></i><b>1.2.2</b> Enduring Resource.</a></li>
<li class="chapter" data-level="1.2.3" data-path="index.html"><a href="index.html#community."><i class="fa fa-check"></i><b>1.2.3</b> Community.</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#concept."><i class="fa fa-check"></i><b>1.3</b> Concept.</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#training-concept"><i class="fa fa-check"></i><b>1.4</b> Training Concept</a><ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#lessons."><i class="fa fa-check"></i><b>1.4.1</b> Lessons.</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#projects."><i class="fa fa-check"></i><b>1.4.2</b> Projects.</a></li>
<li class="chapter" data-level="1.4.3" data-path="index.html"><a href="index.html#assessments."><i class="fa fa-check"></i><b>1.4.3</b> Assessments.</a></li>
<li class="chapter" data-level="1.4.4" data-path="index.html"><a href="index.html#curriculum."><i class="fa fa-check"></i><b>1.4.4</b> Curriculum.</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#community-concept"><i class="fa fa-check"></i><b>1.5</b> Community Concept</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#admin"><i class="fa fa-check"></i><b>1.6</b> Admin</a><ul>
<li class="chapter" data-level="1.6.1" data-path="index.html"><a href="index.html#contact"><i class="fa fa-check"></i><b>1.6.1</b> Contact</a></li>
<li class="chapter" data-level="1.6.2" data-path="index.html"><a href="index.html#errors"><i class="fa fa-check"></i><b>1.6.2</b> Errors</a></li>
<li class="chapter" data-level="1.6.3" data-path="index.html"><a href="index.html#resources"><i class="fa fa-check"></i><b>1.6.3</b> Resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introduction-to-r.html"><a href="introduction-to-r.html"><i class="fa fa-check"></i><b>2</b> Introduction to R</a><ul>
<li class="chapter" data-level="2.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#introduction-to-r---part-i"><i class="fa fa-check"></i><b>2.1</b> Introduction to R - Part I</a><ul>
<li class="chapter" data-level="2.1.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#objectives-1"><i class="fa fa-check"></i><b>2.1.1</b> Objectives</a></li>
<li class="chapter" data-level="2.1.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#task-1---read-chapter-1-and-install-tidyverse"><i class="fa fa-check"></i><b>2.1.2</b> Task 1 - Read Chapter 1 and Install Tidyverse</a></li>
<li class="chapter" data-level="2.1.3" data-path="introduction-to-r.html"><a href="introduction-to-r.html#basic-operations"><i class="fa fa-check"></i><b>2.1.3</b> Basic Operations</a></li>
<li class="chapter" data-level="2.1.4" data-path="introduction-to-r.html"><a href="introduction-to-r.html#variable-types"><i class="fa fa-check"></i><b>2.1.4</b> Variable Types</a></li>
<li class="chapter" data-level="2.1.5" data-path="introduction-to-r.html"><a href="introduction-to-r.html#data-structures"><i class="fa fa-check"></i><b>2.1.5</b> Data Structures</a></li>
<li class="chapter" data-level="2.1.6" data-path="introduction-to-r.html"><a href="introduction-to-r.html#relational-and-logical-operators"><i class="fa fa-check"></i><b>2.1.6</b> Relational and Logical Operators</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#introduction-to-r---part-ii"><i class="fa fa-check"></i><b>2.2</b> Introduction to R - Part II</a><ul>
<li class="chapter" data-level="2.2.1" data-path="introduction-to-r.html"><a href="introduction-to-r.html#reading-tasks"><i class="fa fa-check"></i><b>2.2.1</b> Reading Tasks</a></li>
<li class="chapter" data-level="2.2.2" data-path="introduction-to-r.html"><a href="introduction-to-r.html#problem-set"><i class="fa fa-check"></i><b>2.2.2</b> Problem Set</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="statistics-review.html"><a href="statistics-review.html"><i class="fa fa-check"></i><b>3</b> Statistics Review</a><ul>
<li class="chapter" data-level="3.1" data-path="statistics-review.html"><a href="statistics-review.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a><ul>
<li class="chapter" data-level="3.1.1" data-path="statistics-review.html"><a href="statistics-review.html#resources-1"><i class="fa fa-check"></i><b>3.1.1</b> Resources</a></li>
<li class="chapter" data-level="3.1.2" data-path="statistics-review.html"><a href="statistics-review.html#organization"><i class="fa fa-check"></i><b>3.1.2</b> Organization</a></li>
<li class="chapter" data-level="3.1.3" data-path="statistics-review.html"><a href="statistics-review.html#poc"><i class="fa fa-check"></i><b>3.1.3</b> POC</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="statistics-review.html"><a href="statistics-review.html#descriptive-statistics"><i class="fa fa-check"></i><b>3.2</b> Descriptive Statistics</a><ul>
<li class="chapter" data-level="3.2.1" data-path="statistics-review.html"><a href="statistics-review.html#descriptive-statistics---description"><i class="fa fa-check"></i><b>3.2.1</b> Descriptive Statistics - Description</a></li>
<li class="chapter" data-level="3.2.2" data-path="statistics-review.html"><a href="statistics-review.html#descriptive-statistics---tutorial"><i class="fa fa-check"></i><b>3.2.2</b> Descriptive Statistics - Tutorial</a></li>
<li class="chapter" data-level="3.2.3" data-path="statistics-review.html"><a href="statistics-review.html#descriptive-statistics---problem-set"><i class="fa fa-check"></i><b>3.2.3</b> Descriptive Statistics - Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="statistics-review.html"><a href="statistics-review.html#statistical-concepts"><i class="fa fa-check"></i><b>3.3</b> Statistical Concepts</a><ul>
<li class="chapter" data-level="3.3.1" data-path="statistics-review.html"><a href="statistics-review.html#statistical-concepts---description"><i class="fa fa-check"></i><b>3.3.1</b> Statistical Concepts - Description</a></li>
<li class="chapter" data-level="3.3.2" data-path="statistics-review.html"><a href="statistics-review.html#statistical-concepts---tutorial"><i class="fa fa-check"></i><b>3.3.2</b> Statistical Concepts - Tutorial</a></li>
<li class="chapter" data-level="3.3.3" data-path="statistics-review.html"><a href="statistics-review.html#statistical-concepts---problem-set"><i class="fa fa-check"></i><b>3.3.3</b> Statistical Concepts - Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="statistics-review.html"><a href="statistics-review.html#statistical-inference"><i class="fa fa-check"></i><b>3.4</b> Statistical Inference</a><ul>
<li class="chapter" data-level="3.4.1" data-path="statistics-review.html"><a href="statistics-review.html#statistical-inference---description"><i class="fa fa-check"></i><b>3.4.1</b> Statistical Inference - Description</a></li>
<li class="chapter" data-level="3.4.2" data-path="statistics-review.html"><a href="statistics-review.html#statistical-inference---tutorial"><i class="fa fa-check"></i><b>3.4.2</b> Statistical Inference - Tutorial</a></li>
<li class="chapter" data-level="3.4.3" data-path="statistics-review.html"><a href="statistics-review.html#statistical-inference---conclusion"><i class="fa fa-check"></i><b>3.4.3</b> Statistical Inference - Conclusion</a></li>
<li class="chapter" data-level="3.4.4" data-path="statistics-review.html"><a href="statistics-review.html#statistical-inference---problem-set"><i class="fa fa-check"></i><b>3.4.4</b> Statistical Inference - Problem Set</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html"><i class="fa fa-check"></i><b>4</b> Analysis of Variance (ANOVA)</a><ul>
<li class="chapter" data-level="4.1" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#introduction-1"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#anova-overview"><i class="fa fa-check"></i><b>4.2</b> ANOVA Overview</a><ul>
<li class="chapter" data-level="4.2.1" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#motivation"><i class="fa fa-check"></i><b>4.2.1</b> Motivation</a></li>
<li class="chapter" data-level="4.2.2" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#broad-concept"><i class="fa fa-check"></i><b>4.2.2</b> Broad Concept</a></li>
<li class="chapter" data-level="4.2.3" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#terminology"><i class="fa fa-check"></i><b>4.2.3</b> Terminology</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#single-factor-fixed-effects-anova"><i class="fa fa-check"></i><b>4.3</b> Single Factor, Fixed Effects ANOVA</a><ul>
<li class="chapter" data-level="4.3.1" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#example"><i class="fa fa-check"></i><b>4.3.1</b> Example</a></li>
<li class="chapter" data-level="4.3.2" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#model"><i class="fa fa-check"></i><b>4.3.2</b> Model</a></li>
<li class="chapter" data-level="4.3.3" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#single-factor-anova-assumptions"><i class="fa fa-check"></i><b>4.3.3</b> Single Factor ANOVA Assumptions</a></li>
<li class="chapter" data-level="4.3.4" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#conducting-single-factor-fixed-effects-anova"><i class="fa fa-check"></i><b>4.3.4</b> Conducting Single Factor (Fixed Effects) ANOVA</a></li>
<li class="chapter" data-level="4.3.5" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#single-factor-fixed-effects-anova-problem-set"><i class="fa fa-check"></i><b>4.3.5</b> Single Factor, Fixed Effects ANOVA Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#single-factor-random-effects-model"><i class="fa fa-check"></i><b>4.4</b> Single Factor, Random Effects Model</a><ul>
<li class="chapter" data-level="4.4.1" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#single-factor-random-effects-problem-set"><i class="fa fa-check"></i><b>4.4.1</b> Single Factor, Random Effects Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#two-factor-fixed-effects-anova"><i class="fa fa-check"></i><b>4.5</b> Two Factor, Fixed Effects ANOVA</a><ul>
<li class="chapter" data-level="4.5.1" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#including-interaction-effects"><i class="fa fa-check"></i><b>4.5.1</b> Including Interaction Effects</a></li>
<li class="chapter" data-level="4.5.2" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#two-factor-anova-problem-set"><i class="fa fa-check"></i><b>4.5.2</b> Two Factor ANOVA Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#anova-for-more-than-two-factors"><i class="fa fa-check"></i><b>4.6</b> ANOVA For More Than Two Factors</a><ul>
<li class="chapter" data-level="4.6.1" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#multi-factor-anova-problem-set"><i class="fa fa-check"></i><b>4.6.1</b> Multi-Factor ANOVA Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#multiple-comparisons"><i class="fa fa-check"></i><b>4.7</b> Multiple Comparisons</a><ul>
<li class="chapter" data-level="4.7.1" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#tukey-test-example"><i class="fa fa-check"></i><b>4.7.1</b> Tukey Test Example</a></li>
<li class="chapter" data-level="4.7.2" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#tukey-test-in-r"><i class="fa fa-check"></i><b>4.7.2</b> Tukey Test in R</a></li>
<li class="chapter" data-level="4.7.3" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#tukey-test-multiple-factors"><i class="fa fa-check"></i><b>4.7.3</b> Tukey Test, Multiple Factors</a></li>
<li class="chapter" data-level="4.7.4" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#multiple-comparisons-problem-set"><i class="fa fa-check"></i><b>4.7.4</b> Multiple Comparisons Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#anova-summary"><i class="fa fa-check"></i><b>4.8</b> ANOVA Summary</a><ul>
<li class="chapter" data-level="4.8.1" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#how-to-calculate-anova"><i class="fa fa-check"></i><b>4.8.1</b> How to Calculate ANOVA</a></li>
<li class="chapter" data-level="4.8.2" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#anova-hypothesis-tests"><i class="fa fa-check"></i><b>4.8.2</b> ANOVA Hypothesis Test(s)</a></li>
<li class="chapter" data-level="4.8.3" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#anova-assumptions"><i class="fa fa-check"></i><b>4.8.3</b> ANOVA Assumptions</a></li>
<li class="chapter" data-level="4.8.4" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#multiple-comparisons-1"><i class="fa fa-check"></i><b>4.8.4</b> Multiple Comparisons</a></li>
<li class="chapter" data-level="4.8.5" data-path="analysis-of-variance-anova.html"><a href="analysis-of-variance-anova.html#further-extensions-of-anova"><i class="fa fa-check"></i><b>4.8.5</b> Further Extensions of ANOVA</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html"><i class="fa fa-check"></i><b>5</b> Fundamentals of Design of Experiments</a><ul>
<li class="chapter" data-level="5.1" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#introduction-2"><i class="fa fa-check"></i><b>5.1</b> Introduction</a><ul>
<li class="chapter" data-level="5.1.1" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#admin-1"><i class="fa fa-check"></i><b>5.1.1</b> Admin</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#doe-overview"><i class="fa fa-check"></i><b>5.2</b> DOE Overview</a><ul>
<li class="chapter" data-level="5.2.1" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#what-is-design-of-experiments"><i class="fa fa-check"></i><b>5.2.1</b> What is Design of Experiments?</a></li>
<li class="chapter" data-level="5.2.2" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#why-design-experiments"><i class="fa fa-check"></i><b>5.2.2</b> Why Design Experiments?</a></li>
<li class="chapter" data-level="5.2.3" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#strategies-for-experimental-design"><i class="fa fa-check"></i><b>5.2.3</b> Strategies for Experimental Design</a></li>
<li class="chapter" data-level="5.2.4" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#history-and-applications-of-experimental-design"><i class="fa fa-check"></i><b>5.2.4</b> History and Applications of Experimental Design</a></li>
<li class="chapter" data-level="5.2.5" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#principles"><i class="fa fa-check"></i><b>5.2.5</b> Principles</a></li>
<li class="chapter" data-level="5.2.6" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#guidelines"><i class="fa fa-check"></i><b>5.2.6</b> Guidelines</a></li>
<li class="chapter" data-level="5.2.7" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#problem-set-1"><i class="fa fa-check"></i><b>5.2.7</b> Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#factorial-designs"><i class="fa fa-check"></i><b>5.3</b> Factorial Designs</a><ul>
<li class="chapter" data-level="5.3.1" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#introduction-3"><i class="fa fa-check"></i><b>5.3.1</b> Introduction</a></li>
<li class="chapter" data-level="5.3.2" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#assessing-and-estimating-effects"><i class="fa fa-check"></i><b>5.3.2</b> Assessing and Estimating Effects</a></li>
<li class="chapter" data-level="5.3.3" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#blocking"><i class="fa fa-check"></i><b>5.3.3</b> Blocking</a></li>
<li class="chapter" data-level="5.3.4" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#problem-set-2"><i class="fa fa-check"></i><b>5.3.4</b> Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#k-factorial-design"><i class="fa fa-check"></i><b>5.4</b> <span class="math inline">\(2^K\)</span> Factorial Design</a><ul>
<li class="chapter" data-level="5.4.1" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#introduction-4"><i class="fa fa-check"></i><b>5.4.1</b> Introduction</a></li>
<li class="chapter" data-level="5.4.2" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#coding-variables-and-effects-signs"><i class="fa fa-check"></i><b>5.4.2</b> Coding Variables and Effects Signs</a></li>
<li class="chapter" data-level="5.4.3" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#estimating-effects-and-contrasts"><i class="fa fa-check"></i><b>5.4.3</b> Estimating Effects and Contrasts</a></li>
<li class="chapter" data-level="5.4.4" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#unreplicated-2k-designs"><i class="fa fa-check"></i><b>5.4.4</b> Unreplicated <span class="math inline">\(2^K\)</span> Designs</a></li>
<li class="chapter" data-level="5.4.5" data-path="fundamentals-of-design-of-experiments.html"><a href="fundamentals-of-design-of-experiments.html#problem-set-3"><i class="fa fa-check"></i><b>5.4.5</b> Problem Set</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html"><i class="fa fa-check"></i><b>6</b> Fractional Factorial Designs</a><ul>
<li class="chapter" data-level="6.1" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#introduction-5"><i class="fa fa-check"></i><b>6.1</b> Introduction</a><ul>
<li class="chapter" data-level="6.1.1" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#admin-2"><i class="fa fa-check"></i><b>6.1.1</b> Admin</a></li>
<li class="chapter" data-level="6.1.2" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#overview"><i class="fa fa-check"></i><b>6.1.2</b> Overview</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#frac12-fractional-factorial-design-2k-1"><i class="fa fa-check"></i><b>6.2</b> <span class="math inline">\(\frac{1}{2}\)</span> Fractional Factorial Design (<span class="math inline">\(2^{K-1}\)</span>)</a><ul>
<li class="chapter" data-level="6.2.1" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#motivation-and-example"><i class="fa fa-check"></i><b>6.2.1</b> Motivation and Example</a></li>
<li class="chapter" data-level="6.2.2" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#design-generator"><i class="fa fa-check"></i><b>6.2.2</b> Design Generator</a></li>
<li class="chapter" data-level="6.2.3" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#estimating-effects"><i class="fa fa-check"></i><b>6.2.3</b> Estimating Effects</a></li>
<li class="chapter" data-level="6.2.4" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#geometric-view"><i class="fa fa-check"></i><b>6.2.4</b> Geometric View</a></li>
<li class="chapter" data-level="6.2.5" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#example-24-1-design"><i class="fa fa-check"></i><b>6.2.5</b> Example <span class="math inline">\(2^{4-1}\)</span> Design</a></li>
<li class="chapter" data-level="6.2.6" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#frac12-fractional-factorial-design-2k-1-problem-set"><i class="fa fa-check"></i><b>6.2.6</b> <span class="math inline">\(\frac{1}{2}\)</span> Fractional Factorial Design (<span class="math inline">\(2^{K-1}\)</span>) Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#general-2k-p-designs"><i class="fa fa-check"></i><b>6.3</b> General <span class="math inline">\(2^{K-P}\)</span> Designs</a><ul>
<li class="chapter" data-level="6.3.1" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#introduction-6"><i class="fa fa-check"></i><b>6.3.1</b> Introduction</a></li>
<li class="chapter" data-level="6.3.2" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#quarter-fractional-design"><i class="fa fa-check"></i><b>6.3.2</b> Quarter Fractional Design</a></li>
<li class="chapter" data-level="6.3.3" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#general-2k-p-design"><i class="fa fa-check"></i><b>6.3.3</b> General <span class="math inline">\(2^{K-P}\)</span> Design</a></li>
<li class="chapter" data-level="6.3.4" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#resolution"><i class="fa fa-check"></i><b>6.3.4</b> Resolution</a></li>
<li class="chapter" data-level="6.3.5" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#general-2k-p-designs-problem-set"><i class="fa fa-check"></i><b>6.3.5</b> General <span class="math inline">\(2^{K-P}\)</span> Designs Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#additional-notes-on-2k-p-designs"><i class="fa fa-check"></i><b>6.4</b> Additional Notes on <span class="math inline">\(2^{K-P}\)</span> Designs</a><ul>
<li class="chapter" data-level="6.4.1" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#additional-topics"><i class="fa fa-check"></i><b>6.4.1</b> Additional Topics</a></li>
<li class="chapter" data-level="6.4.2" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#sequencing-experiments"><i class="fa fa-check"></i><b>6.4.2</b> Sequencing Experiments</a></li>
<li class="chapter" data-level="6.4.3" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#fractional-factorial-design-simulation-problem-set"><i class="fa fa-check"></i><b>6.4.3</b> Fractional Factorial Design Simulation Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#screening-experiments-and-selecting-factors"><i class="fa fa-check"></i><b>6.5</b> Screening Experiments and Selecting Factors</a></li>
<li class="chapter" data-level="6.6" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#conclusion"><i class="fa fa-check"></i><b>6.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html"><i class="fa fa-check"></i><b>7</b> Fundamentals of Regression</a><ul>
<li class="chapter" data-level="7.1" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#admin-3"><i class="fa fa-check"></i><b>7.1</b> Admin</a></li>
<li class="chapter" data-level="7.2" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>7.2</b> Simple Linear Regression</a><ul>
<li class="chapter" data-level="7.2.1" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#least-squares-method-manually"><i class="fa fa-check"></i><b>7.2.1</b> Least Squares Method Manually</a></li>
<li class="chapter" data-level="7.2.2" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#goodness-of-fit"><i class="fa fa-check"></i><b>7.2.2</b> Goodness of Fit</a></li>
<li class="chapter" data-level="7.2.3" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#least-squares-method-in-r"><i class="fa fa-check"></i><b>7.2.3</b> Least Squares Method In <em>R</em></a></li>
<li class="chapter" data-level="7.2.4" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#simple-linear-regression-problem-set"><i class="fa fa-check"></i><b>7.2.4</b> Simple Linear Regression Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#assumptions-and-diagnostics"><i class="fa fa-check"></i><b>7.3</b> Assumptions and Diagnostics</a><ul>
<li class="chapter" data-level="7.3.1" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#linearity"><i class="fa fa-check"></i><b>7.3.1</b> Linearity</a></li>
<li class="chapter" data-level="7.3.2" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#homoscedasticity"><i class="fa fa-check"></i><b>7.3.2</b> Homoscedasticity</a></li>
<li class="chapter" data-level="7.3.3" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#independence"><i class="fa fa-check"></i><b>7.3.3</b> Independence</a></li>
<li class="chapter" data-level="7.3.4" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#normality"><i class="fa fa-check"></i><b>7.3.4</b> Normality</a></li>
<li class="chapter" data-level="7.3.5" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#unusual-observations"><i class="fa fa-check"></i><b>7.3.5</b> Unusual Observations</a></li>
<li class="chapter" data-level="7.3.6" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#linear-regression-assumptions-and-diagnostics-problem-set"><i class="fa fa-check"></i><b>7.3.6</b> Linear Regression Assumptions and Diagnostics Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#multiple-linear-regression"><i class="fa fa-check"></i><b>7.4</b> Multiple Linear Regression</a><ul>
<li class="chapter" data-level="7.4.1" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#r-example"><i class="fa fa-check"></i><b>7.4.1</b> <em>R</em> Example</a></li>
<li class="chapter" data-level="7.4.2" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#multiple-linear-regression-problem-set"><i class="fa fa-check"></i><b>7.4.2</b> Multiple Linear Regression Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#categorical-variables"><i class="fa fa-check"></i><b>7.5</b> Categorical Variables</a><ul>
<li class="chapter" data-level="7.5.1" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#categorical-linear-regression-problem-set"><i class="fa fa-check"></i><b>7.5.1</b> Categorical Linear Regression Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#transformation"><i class="fa fa-check"></i><b>7.6</b> Transformation</a><ul>
<li class="chapter" data-level="7.6.1" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#identifying-non-linear-relationships"><i class="fa fa-check"></i><b>7.6.1</b> Identifying Non-Linear Relationships</a></li>
<li class="chapter" data-level="7.6.2" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#checking-model-structure"><i class="fa fa-check"></i><b>7.6.2</b> Checking Model Structure</a></li>
<li class="chapter" data-level="7.6.3" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#how-to-transform-variables-in-r"><i class="fa fa-check"></i><b>7.6.3</b> How To Transform Variables In <em>R</em></a></li>
<li class="chapter" data-level="7.6.4" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#transformed-regression-problem-set"><i class="fa fa-check"></i><b>7.6.4</b> Transformed Regression Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#logistic-regression"><i class="fa fa-check"></i><b>7.7</b> Logistic Regression</a><ul>
<li class="chapter" data-level="7.7.1" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#motivating-example"><i class="fa fa-check"></i><b>7.7.1</b> Motivating Example</a></li>
<li class="chapter" data-level="7.7.2" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#logit-function"><i class="fa fa-check"></i><b>7.7.2</b> Logit Function</a></li>
<li class="chapter" data-level="7.7.3" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#logistic-regression-in-r"><i class="fa fa-check"></i><b>7.7.3</b> Logistic Regression in <em>R</em></a></li>
<li class="chapter" data-level="7.7.4" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#logistic-regression-diagnostics"><i class="fa fa-check"></i><b>7.7.4</b> Logistic Regression Diagnostics</a></li>
<li class="chapter" data-level="7.7.5" data-path="fundamentals-of-regression.html"><a href="fundamentals-of-regression.html#logistic-regression-problem-set"><i class="fa fa-check"></i><b>7.7.5</b> Logistic Regression Problem Set</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="model-selection.html"><a href="model-selection.html"><i class="fa fa-check"></i><b>8</b> Model Selection</a><ul>
<li class="chapter" data-level="8.1" data-path="model-selection.html"><a href="model-selection.html#admin-4"><i class="fa fa-check"></i><b>8.1</b> Admin</a></li>
<li class="chapter" data-level="8.2" data-path="model-selection.html"><a href="model-selection.html#introduction-7"><i class="fa fa-check"></i><b>8.2</b> Introduction</a></li>
<li class="chapter" data-level="8.3" data-path="model-selection.html"><a href="model-selection.html#testing-based-methods"><i class="fa fa-check"></i><b>8.3</b> Testing-Based Methods</a></li>
<li class="chapter" data-level="8.4" data-path="model-selection.html"><a href="model-selection.html#criterion-based-methods"><i class="fa fa-check"></i><b>8.4</b> Criterion-Based Methods</a><ul>
<li class="chapter" data-level="8.4.1" data-path="model-selection.html"><a href="model-selection.html#criterion-problem-set"><i class="fa fa-check"></i><b>8.4.1</b> Criterion Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="model-selection.html"><a href="model-selection.html#cross-validation"><i class="fa fa-check"></i><b>8.5</b> Cross Validation</a><ul>
<li class="chapter" data-level="8.5.1" data-path="model-selection.html"><a href="model-selection.html#what-about-the-test-set"><i class="fa fa-check"></i><b>8.5.1</b> What About The Test Set?</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="model-selection.html"><a href="model-selection.html#lasso-regression"><i class="fa fa-check"></i><b>8.6</b> Lasso Regression</a><ul>
<li class="chapter" data-level="8.6.1" data-path="model-selection.html"><a href="model-selection.html#background-reading"><i class="fa fa-check"></i><b>8.6.1</b> Background Reading</a></li>
<li class="chapter" data-level="8.6.2" data-path="model-selection.html"><a href="model-selection.html#lasso-regression-in-r"><i class="fa fa-check"></i><b>8.6.2</b> Lasso Regression In R</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="model-selection.html"><a href="model-selection.html#parting-thought"><i class="fa fa-check"></i><b>8.7</b> Parting Thought</a></li>
<li class="chapter" data-level="8.8" data-path="model-selection.html"><a href="model-selection.html#lasso-regression-problem-set"><i class="fa fa-check"></i><b>8.8</b> Lasso Regression Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="application-of-doe-to-the-advanced-warfighting-simulation.html"><a href="application-of-doe-to-the-advanced-warfighting-simulation.html"><i class="fa fa-check"></i><b>9</b> Application of DoE to the Advanced Warfighting Simulation</a></li>
<li class="chapter" data-level="10" data-path="advanced-experimental-designs.html"><a href="advanced-experimental-designs.html"><i class="fa fa-check"></i><b>10</b> Advanced Experimental Designs</a><ul>
<li class="chapter" data-level="10.1" data-path="advanced-experimental-designs.html"><a href="advanced-experimental-designs.html#admin-5"><i class="fa fa-check"></i><b>10.1</b> Admin</a></li>
<li class="chapter" data-level="10.2" data-path="advanced-experimental-designs.html"><a href="advanced-experimental-designs.html#introduction-and-background"><i class="fa fa-check"></i><b>10.2</b> Introduction and Background</a></li>
<li class="chapter" data-level="10.3" data-path="advanced-experimental-designs.html"><a href="advanced-experimental-designs.html#central-composite-designs"><i class="fa fa-check"></i><b>10.3</b> Central Composite Designs</a><ul>
<li class="chapter" data-level="10.3.1" data-path="advanced-experimental-designs.html"><a href="advanced-experimental-designs.html#augmented-central-composite-designs"><i class="fa fa-check"></i><b>10.3.1</b> Augmented Central Composite Designs</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="advanced-experimental-designs.html"><a href="advanced-experimental-designs.html#response-surface-methodology"><i class="fa fa-check"></i><b>10.4</b> Response Surface Methodology</a><ul>
<li class="chapter" data-level="10.4.1" data-path="advanced-experimental-designs.html"><a href="advanced-experimental-designs.html#ccd-problem-set"><i class="fa fa-check"></i><b>10.4.1</b> CCD Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="advanced-experimental-designs.html"><a href="advanced-experimental-designs.html#nearly-orthogonal-latin-hypercube-designs"><i class="fa fa-check"></i><b>10.5</b> Nearly Orthogonal Latin Hypercube Designs</a><ul>
<li class="chapter" data-level="10.5.1" data-path="advanced-experimental-designs.html"><a href="advanced-experimental-designs.html#factor-codings"><i class="fa fa-check"></i><b>10.5.1</b> Factor Codings</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="advanced-experimental-designs.html"><a href="advanced-experimental-designs.html#orthogonality-and-variance-inflation-factors"><i class="fa fa-check"></i><b>10.6</b> Orthogonality and Variance Inflation Factors</a></li>
<li class="chapter" data-level="10.7" data-path="advanced-experimental-designs.html"><a href="advanced-experimental-designs.html#shifting-and-stacking"><i class="fa fa-check"></i><b>10.7</b> Shifting and Stacking</a><ul>
<li class="chapter" data-level="10.7.1" data-path="advanced-experimental-designs.html"><a href="advanced-experimental-designs.html#nolh-problem-set"><i class="fa fa-check"></i><b>10.7.1</b> NOLH Problem Set</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html"><i class="fa fa-check"></i><b>11</b> Non-Parametric Regression</a><ul>
<li class="chapter" data-level="11.1" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#admin-6"><i class="fa fa-check"></i><b>11.1</b> Admin</a></li>
<li class="chapter" data-level="11.2" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#non-parametric-anova"><i class="fa fa-check"></i><b>11.2</b> Non-Parametric ANOVA</a><ul>
<li class="chapter" data-level="11.2.1" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#multiple-comparisons-2"><i class="fa fa-check"></i><b>11.2.1</b> Multiple Comparisons</a></li>
<li class="chapter" data-level="11.2.2" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#non-parametric-anova-problem-set"><i class="fa fa-check"></i><b>11.2.2</b> Non-Parametric ANOVA Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#generalized-additive-models"><i class="fa fa-check"></i><b>11.3</b> Generalized Additive Models</a><ul>
<li class="chapter" data-level="11.3.1" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#loess"><i class="fa fa-check"></i><b>11.3.1</b> Loess</a></li>
<li class="chapter" data-level="11.3.2" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#splines"><i class="fa fa-check"></i><b>11.3.2</b> Splines</a></li>
<li class="chapter" data-level="11.3.3" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#cross-validation-1"><i class="fa fa-check"></i><b>11.3.3</b> Cross Validation</a></li>
<li class="chapter" data-level="11.3.4" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#gam-problem-set"><i class="fa fa-check"></i><b>11.3.4</b> GAM Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#support-vector-machines"><i class="fa fa-check"></i><b>11.4</b> Support Vector Machines</a><ul>
<li class="chapter" data-level="11.4.1" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#support-vector-regression"><i class="fa fa-check"></i><b>11.4.1</b> Support Vector Regression</a></li>
<li class="chapter" data-level="11.4.2" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#support-vector-classification"><i class="fa fa-check"></i><b>11.4.2</b> Support Vector Classification</a></li>
<li class="chapter" data-level="11.4.3" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#svm-problem-set"><i class="fa fa-check"></i><b>11.4.3</b> SVM Problem Set</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#classification-and-regression-trees"><i class="fa fa-check"></i><b>11.5</b> Classification and Regression Trees</a><ul>
<li class="chapter" data-level="11.5.1" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#regression-trees"><i class="fa fa-check"></i><b>11.5.1</b> Regression Trees</a></li>
<li class="chapter" data-level="11.5.2" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#random-forest-regression"><i class="fa fa-check"></i><b>11.5.2</b> Random Forest Regression</a></li>
<li class="chapter" data-level="11.5.3" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#random-forest-classification"><i class="fa fa-check"></i><b>11.5.3</b> Random Forest Classification</a></li>
<li class="chapter" data-level="11.5.4" data-path="non-parametric-regression.html"><a href="non-parametric-regression.html#cart-problem-set"><i class="fa fa-check"></i><b>11.5.4</b> CART Problem Set</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="optional-advanced-doe-topics.html"><a href="optional-advanced-doe-topics.html"><i class="fa fa-check"></i><b>12</b> Optional Advanced DOE Topics</a><ul>
<li class="chapter" data-level="12.1" data-path="optional-advanced-doe-topics.html"><a href="optional-advanced-doe-topics.html#robust-design"><i class="fa fa-check"></i><b>12.1</b> Robust Design</a></li>
<li class="chapter" data-level="12.2" data-path="optional-advanced-doe-topics.html"><a href="optional-advanced-doe-topics.html#sequential-designs"><i class="fa fa-check"></i><b>12.2</b> Sequential Designs</a></li>
<li class="chapter" data-level="12.3" data-path="optional-advanced-doe-topics.html"><a href="optional-advanced-doe-topics.html#ridge-regression"><i class="fa fa-check"></i><b>12.3</b> Ridge Regression</a></li>
<li class="chapter" data-level="12.4" data-path="optional-advanced-doe-topics.html"><a href="optional-advanced-doe-topics.html#neural-network-regression"><i class="fa fa-check"></i><b>12.4</b> Neural Network Regression</a><ul>
<li class="chapter" data-level="12.4.1" data-path="optional-advanced-doe-topics.html"><a href="optional-advanced-doe-topics.html#simple-neural-network-model"><i class="fa fa-check"></i><b>12.4.1</b> Simple Neural Network Model</a></li>
<li class="chapter" data-level="12.4.2" data-path="optional-advanced-doe-topics.html"><a href="optional-advanced-doe-topics.html#gradient-descent"><i class="fa fa-check"></i><b>12.4.2</b> Gradient Descent</a></li>
<li class="chapter" data-level="12.4.3" data-path="optional-advanced-doe-topics.html"><a href="optional-advanced-doe-topics.html#multiple-linear-regression-1"><i class="fa fa-check"></i><b>12.4.3</b> Multiple Linear Regression</a></li>
<li class="chapter" data-level="12.4.4" data-path="optional-advanced-doe-topics.html"><a href="optional-advanced-doe-topics.html#hidden-layer"><i class="fa fa-check"></i><b>12.4.4</b> Hidden Layer</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="optional-advanced-doe-topics.html"><a href="optional-advanced-doe-topics.html#neural-network-classification"><i class="fa fa-check"></i><b>12.5</b> Neural Network Classification</a></li>
<li class="chapter" data-level="12.6" data-path="optional-advanced-doe-topics.html"><a href="optional-advanced-doe-topics.html#multivariate-adaptive-regression-splines"><i class="fa fa-check"></i><b>12.6</b> Multivariate Adaptive Regression Splines</a></li>
<li class="chapter" data-level="12.7" data-path="optional-advanced-doe-topics.html"><a href="optional-advanced-doe-topics.html#non-parametric-statistics"><i class="fa fa-check"></i><b>12.7</b> Non-Parametric Statistics</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown">
Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Design of Experiments for Modeling and Simulation</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistics-review" class="section level1">
<h1><span class="header-section-number">3</span> Statistics Review</h1>
<div id="introduction" class="section level2">
<h2><span class="header-section-number">3.1</span> Introduction</h2>
<p>In this section, we will briefly review the probability and statistics topics that are relevant to the design and analysis of experiments for modeling and simulation. In particular, we will cover:</p>
<ul>
<li>Descriptive Statistics</li>
<li>Statistical Concepts</li>
<li>Statistical Inference</li>
<li>Analysis of Variance</li>
</ul>
<div id="resources-1" class="section level3">
<h3><span class="header-section-number">3.1.1</span> Resources</h3>
<p>The following are useful resources to review these topics:</p>
<ul>
<li><a href = "https://www.khanacademy.org/math/ap-statistics"> The Khan Academy AP Statistics Course </a></li>
<li><a href = "https://ocw.mit.edu/courses/mathematics/18-05-introduction-to-probability-and-statistics-spring-2014/index.htm"> The MIT Open Courseware <em>Introduction to Probability and Statistics</em> taught by Orloff and Bloom in Spring 2014 </a></li>
<li>Any standard probability and statistics text, e.g.:
<ul>
<li><a href = "https://www.cengage.com/c/probability-and-statistics-for-engineering-and-the-sciences-9e-devore/9781305251809PF/"> Devore’s *Probability and Statistics for Engineering and the Sciences</a></li>
<li><a href="https://www.cengage.com/c/probability-and-statistics-for-engineers-and-scientists-4e-hayter/9781111827045/"> Hayter’s Probability and Statistics for Engineers and Scientists </a></li>
<li>Please note, there is no need to buy anything or especially the latest version. Older versions are almost always perfectly accurate and significantly cheaper.</li>
<li>There are a variety of free texts, for example: <a href = "https://moderndive.com/"><em>Statistical Inference via Data Science</em></a> hosted via <a href = 'https://bookdown.org'>Bookdown</a> is nice. The <a href = "https://www.itl.nist.gov/div898/handbook/"><em>NIST Engineering Statistics</em></a> from NIST is also incredibly useful.</li>
</ul></li>
</ul>
<p>Given the extensive coverage of these topics, most of this section will be terse and/or refer to external resources as anything I might write is likely redundant. That stated, if you are familiar with these topics, try your hand at the problem sets if you’re rusty or have not ever done statistics using <em>R</em>.</p>
</div>
<div id="organization" class="section level3">
<h3><span class="header-section-number">3.1.2</span> Organization</h3>
<p>The remainder of this chapter is organized as follows:</p>
<ul>
<li>Lesson
<ul>
<li>Lesson Description</li>
<li>Lesson Tutorial</li>
<li>Lesson Problem Set</li>
</ul></li>
</ul>
</div>
<div id="poc" class="section level3">
<h3><span class="header-section-number">3.1.3</span> POC</h3>
<p>For any noted issues (especially errors), please contact: Steve Gillespie at <a href="mailto:stephen.e.gillespie.mil@mail.mil" class="email">stephen.e.gillespie.mil@mail.mil</a> or Emma Schlagenhauff at <a href="mailto:emma.schlagenhauff.civ@mail.mil" class="email">emma.schlagenhauff.civ@mail.mil</a>.</p>
</div>
</div>
<div id="descriptive-statistics" class="section level2">
<h2><span class="header-section-number">3.2</span> Descriptive Statistics</h2>
<div id="descriptive-statistics---description" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Descriptive Statistics - Description</h3>
<p>This section is a refresher for analysts on basic descriptive statistics including the following concepts:</p>
<ul>
<li>Measures of central tendency: mean, median, mode.</li>
<li>Measures of dispersion: standard deviation and variance, interquartile range, and range.</li>
<li>Standard plots including: boxplots, histograms, density plots.</li>
<li>Empirical probability distributions and cumulative distribution functions.</li>
</ul>
</div>
<div id="descriptive-statistics---tutorial" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Descriptive Statistics - Tutorial</h3>
<p>For this tutorial, we assume one is familiar with the measures identified above. If not, please view the following videos:</p>
<ul>
<li><a href = "https://www.khanacademy.org/math/ap-statistics/quantitative-data-ap"> Khan Academy AP Statistics Displaying and Describing Quantitative Data </a></li>
<li><a href = "https://www.khanacademy.org/math/ap-statistics/summarizing-quantitative-data-ap"> Khan Academy AP Statistics Summarizing Quantitative Data </a></li>
<li><a href = "https://www.khanacademy.org/math/ap-statistics/density-curves-normal-distribution-ap"> Khan Academy AP Statistics Modeling Data Distributions </a></li>
</ul>
<p>The remainder of this tutorial is simply brief concept descriptions and examples in R.</p>
<div id="measures-of-central-tendency" class="section level4">
<h4><span class="header-section-number">3.2.2.1</span> Measures of Central Tendency</h4>
<div id="mean" class="section level5">
<h5><span class="header-section-number">3.2.2.1.1</span> Mean</h5>
<p>The mean of a set of <span class="math inline">\(n\)</span> numbers: <span class="math inline">\({a_1, a_2, ... a_n}\)</span> is <span class="math inline">\(\frac{\sum_{i=1}^na_i}{n}\)</span></p>
<p>In <em>R</em> we can calculate the mean of a vector as follows:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb214-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="dv">0</span><span class="op">:</span><span class="dv">10</span></a>
<a class="sourceLine" id="cb214-2" data-line-number="2">x</a></code></pre></div>
<pre><code>##  [1]  0  1  2  3  4  5  6  7  8  9 10</code></pre>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" data-line-number="1"><span class="kw">mean</span>(x)</a></code></pre></div>
<pre><code>## [1] 5</code></pre>
</div>
<div id="median" class="section level5">
<h5><span class="header-section-number">3.2.2.1.2</span> Median</h5>
<p>The mean of a set of <span class="math inline">\(n\)</span> numbers as listed above is:</p>
<ul>
<li>If the set is finite and has odd cardinality, the number “in the middle” of the set when ordered.</li>
<li>If the set is finite and has even cardinality, the average of the two numbers “in the middle” of the set when ordered.</li>
<li>If the set is infinite, the value of the 50 percentile.</li>
</ul>
<p>Using the same data as above <code>x</code>, we can calculate the median as:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb218-1" data-line-number="1"><span class="kw">median</span>(x)</a></code></pre></div>
<pre><code>## [1] 5</code></pre>
</div>
<div id="mean-and-median-note---treatment-of-na" class="section level5">
<h5><span class="header-section-number">3.2.2.1.3</span> Mean and Median Note - Treatment of NA</h5>
<p>As you may have experienced, often data sets are incomplete. In <em>R</em> these missing values are often represented as <code>NA</code>. Both <code>mean()</code> and <code>median()</code> have an argument called <code>na.rm</code> that is defaulted to <code>FALSE</code>. Let’s see what happens:</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb220-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">c</span>(x, <span class="ot">NA</span>) <span class="co"># Add an NA to the data set</span></a>
<a class="sourceLine" id="cb220-2" data-line-number="2">x</a></code></pre></div>
<pre><code>##  [1]  0  1  2  3  4  5  6  7  8  9 10 NA</code></pre>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb222-1" data-line-number="1"><span class="co"># The mean and median will return NA</span></a>
<a class="sourceLine" id="cb222-2" data-line-number="2"><span class="kw">mean</span>(x)</a></code></pre></div>
<pre><code>## [1] NA</code></pre>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb224-1" data-line-number="1"><span class="kw">median</span>(x)</a></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>This is a logical result as it lets us know we really can’t determine the mean (you can’t sum an NA either). If you want to drop the NAs and calculate the mean or median with only the values available (understanding that you are missing data), you can do this by changing the default for <code>na.rm</code> as follows:</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" data-line-number="1">x</a></code></pre></div>
<pre><code>##  [1]  0  1  2  3  4  5  6  7  8  9 10 NA</code></pre>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" data-line-number="1"><span class="kw">mean</span>(x, <span class="dt">na.rm =</span> T)</a></code></pre></div>
<pre><code>## [1] 5</code></pre>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" data-line-number="1"><span class="kw">median</span>(x, <span class="dt">na.rm =</span> T)</a></code></pre></div>
<pre><code>## [1] 5</code></pre>
</div>
<div id="mode" class="section level5">
<h5><span class="header-section-number">3.2.2.1.4</span> Mode</h5>
<p>The mode of a discrete set of numbers is the number (or numbers) that occurs most frequently in the set.</p>
<p>Inexplicably, <em>R</em> does not have a base function for mode. If you want to find the mode of a set, you can solve this problem in any number of ways. Here is one approach, I recommend you trying to do this in a different way!</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb232-1" data-line-number="1">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="kw">rep</span>(<span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>), <span class="dv">5</span>))</a>
<a class="sourceLine" id="cb232-2" data-line-number="2">y</a></code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10  2  3  2  3  2  3  2  3  2  3</code></pre>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb234-1" data-line-number="1"><span class="co"># Note that the mode is not what you would expect. It tells you something about the data type</span></a>
<a class="sourceLine" id="cb234-2" data-line-number="2"><span class="kw">mode</span>(y)</a></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb236-1" data-line-number="1"><span class="co"># Create a data frame with the values of y, then group by the individual values and count them.  I&#39;ll use dplyr to manipulate the dataframe</span></a>
<a class="sourceLine" id="cb236-2" data-line-number="2"><span class="kw">library</span>(dplyr)</a>
<a class="sourceLine" id="cb236-3" data-line-number="3">myDF &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">Num =</span> y)</a>
<a class="sourceLine" id="cb236-4" data-line-number="4">myDF &lt;-<span class="st"> </span>myDF <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">group_by</span>(Num) <span class="op">%&gt;%</span><span class="st"> </span>dplyr<span class="op">::</span><span class="kw">summarise</span>(<span class="dt">Count =</span> <span class="kw">n</span>(), <span class="dt">.groups=</span><span class="st">&#39;drop&#39;</span>) <span class="co"># We create a data frame that gives us the count of y </span></a>
<a class="sourceLine" id="cb236-5" data-line-number="5">myDF</a></code></pre></div>
<pre><code>## # A tibble: 10 x 2
##      Num Count
##  * &lt;dbl&gt; &lt;int&gt;
##  1     1     1
##  2     2     6
##  3     3     6
##  4     4     1
##  5     5     1
##  6     6     1
##  7     7     1
##  8     8     1
##  9     9     1
## 10    10     1</code></pre>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb238-1" data-line-number="1">myMode &lt;-<span class="st"> </span>myDF<span class="op">$</span>Num[myDF<span class="op">$</span>Count <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(myDF<span class="op">$</span>Count)]</a>
<a class="sourceLine" id="cb238-2" data-line-number="2">myMode</a></code></pre></div>
<pre><code>## [1] 2 3</code></pre>
<p>While that is a bit annoying, if one was frequently finding the mode of a set, we could define a function that does this and save it and reference it later.</p>
</div>
</div>
<div id="measures-of-dispersion" class="section level4">
<h4><span class="header-section-number">3.2.2.2</span> Measures of Dispersion</h4>
<div id="standard-deviation" class="section level5">
<h5><span class="header-section-number">3.2.2.2.1</span> Standard Deviation</h5>
<p>The standard deviation <span class="math inline">\(\sigma\)</span> and variance <span class="math inline">\(\sigma^2\)</span> of a set of numbers measures the “spread” or “dispersion” of the set of data from its mean. It is calculated as:</p>
<ul>
<li><span class="math inline">\(\sigma = \sqrt{\frac{\sum(x_i - \mu)^2}{N}}\)</span> where <span class="math inline">\(\mu\)</span> is the population mean.</li>
</ul>
<p>Often we do not know the population mean and estimate it from the sample, so we must get the sample standard deviation as:</p>
<ul>
<li><span class="math inline">\(s = \sqrt{\frac{\sum(x_i - x\bar)^2}{N-1}}\)</span> where <span class="math inline">\(\bar{x}\)</span> is the sample mean.</li>
</ul>
<p><em>R</em> defaults to use the sample standard deviation and variance (i.e., the <span class="math inline">\(N-1\)</span> denominator), though for sufficiently large sample sizes, the effect of this is minimal.</p>
<p>Let’s see how to do this:</p>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb240-1" data-line-number="1"><span class="co"># Create a random set of data.  We&#39;ll use the function rnorm(n, mean, standard deviation) </span></a>
<a class="sourceLine" id="cb240-2" data-line-number="2"><span class="co"># which produces random numbers from a normal distribution with the provided mean and the </span></a>
<a class="sourceLine" id="cb240-3" data-line-number="3"><span class="co"># provided standard deviation.</span></a>
<a class="sourceLine" id="cb240-4" data-line-number="4">x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">30</span>, <span class="dt">mean =</span> <span class="dv">10</span>, <span class="dt">sd =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb240-5" data-line-number="5">x</a></code></pre></div>
<pre><code>##  [1]  9.481679 10.106188  8.030881 10.153189  6.405635 10.999582  5.192514
##  [8]  9.559060  8.409480 11.205995 13.337560  6.865334  9.307742 11.170984
## [15]  9.622531 10.493340  8.204369  9.531700 12.531379  8.212803 10.215235
## [22] 11.246772  7.921006  7.926419  8.722660  9.858107 15.180443  9.387789
## [29] 14.657690 10.749475</code></pre>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb242-1" data-line-number="1"><span class="kw">mean</span>(x)</a></code></pre></div>
<pre><code>## [1] 9.822918</code></pre>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb244-1" data-line-number="1"><span class="kw">sd</span>(x)</a></code></pre></div>
<pre><code>## [1] 2.213116</code></pre>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb246-1" data-line-number="1"><span class="kw">var</span>(x)</a></code></pre></div>
<pre><code>## [1] 4.897881</code></pre>
<p>Note that the provided (i.e., true) mean is 10 and the provided (i.e, true) standard deviation is 2, but our estimates are just that, statistical estimates.</p>
</div>
<div id="median-absolute-deviation" class="section level5">
<h5><span class="header-section-number">3.2.2.2.2</span> Median Absolute Deviation</h5>
<p>The median absolute deviation (MAD) is a robust measure of the spread of a set of data. It is <em>robust</em> in the sense that it is not highly sensitive to outliers or non-normality. The MAD is defined as the median of the absolute value of the difference between each observation in a set and the set’s median:</p>
<p><span class="math inline">\(MAD = median(|Y_i - median(Y)|)\)</span></p>
<p>Where <span class="math inline">\(Y_i \in Y\)</span> and Y is the set under question.</p>
<p>For example, consider the set: <span class="math inline">\(Y = 1, 2, 3... 10\)</span>. This set has a median of 5.5. We can then make a new set, <span class="math inline">\(W\)</span>, of the absolute value of the difference between the median and the observation, i.e.:</p>
<p><span class="math inline">\(W = {|1-5.5|, |2-5.5|,|3-5.5|, ... |10-5.5|} = {4.5, 3.5, 2.5, ..., 4.5}\)</span></p>
<p>The MAD is then the median of <span class="math inline">\(W\)</span>. We can calculate this as follows:</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb248-1" data-line-number="1">Y &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span> <span class="co"># Define Y as the set 1, 2, .. 10</span></a>
<a class="sourceLine" id="cb248-2" data-line-number="2">Y</a></code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb250-1" data-line-number="1">Y.median &lt;-<span class="st"> </span><span class="kw">median</span>(Y) <span class="co"># Calculate the median of Y</span></a>
<a class="sourceLine" id="cb250-2" data-line-number="2">Y.median</a></code></pre></div>
<pre><code>## [1] 5.5</code></pre>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb252-1" data-line-number="1"><span class="co"># Note how R applies the operation below to each member of the vector</span></a>
<a class="sourceLine" id="cb252-2" data-line-number="2">W &lt;-<span class="st"> </span><span class="kw">abs</span>(Y<span class="op">-</span>Y.median) <span class="co"># Define W as the set of the absolute value of the difference between Y and its median</span></a>
<a class="sourceLine" id="cb252-3" data-line-number="3">W</a></code></pre></div>
<pre><code>##  [1] 4.5 3.5 2.5 1.5 0.5 0.5 1.5 2.5 3.5 4.5</code></pre>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb254-1" data-line-number="1">W.median &lt;-<span class="st"> </span><span class="kw">median</span>(W)</a>
<a class="sourceLine" id="cb254-2" data-line-number="2">W.median</a></code></pre></div>
<pre><code>## [1] 2.5</code></pre>
<p>So, we see that the <span class="math inline">\(MAD\)</span> of {1, 2, …10} is 2.5. Of course, the above coding was onerous; fortunately, <em>R</em> has a function, <code>mad()</code> to do this for us; however, the default in <em>R</em> is to add a normalizing factor above and beyond the standard <span class="math inline">\(MAD\)</span> calculation. What <code>mad()</code> returns is the <span class="math inline">\(MAD\)</span> as defined above times a constant. In <em>R</em>, the default constant is 1.4826 (read the <em>R</em> help on <code>mad()</code> for an explanation as to why). If you simply want the standard <span class="math inline">\(MAD\)</span>, adjust the constant to 1 as seen below:</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb256-1" data-line-number="1"><span class="kw">mad</span>(Y, <span class="dt">constant =</span> <span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 2.5</code></pre>
</div>
<div id="range" class="section level5">
<h5><span class="header-section-number">3.2.2.2.3</span> Range</h5>
<p>While not a typical statistic, it is often useful to know the maximum and minimum of a set, and, sometimes, their difference. These numbers are self explanatory and can be quickly computed in <em>R</em> as follows:</p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb258-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">100</span> <span class="co"># Note the max is 100 and the minimum is 1</span></a>
<a class="sourceLine" id="cb258-2" data-line-number="2"></a>
<a class="sourceLine" id="cb258-3" data-line-number="3"><span class="co"># Maximum</span></a>
<a class="sourceLine" id="cb258-4" data-line-number="4"><span class="kw">max</span>(x)</a></code></pre></div>
<pre><code>## [1] 100</code></pre>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb260-1" data-line-number="1"><span class="co"># Minimum</span></a>
<a class="sourceLine" id="cb260-2" data-line-number="2"><span class="kw">min</span>(x)</a></code></pre></div>
<pre><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb262-1" data-line-number="1"><span class="co"># Both</span></a>
<a class="sourceLine" id="cb262-2" data-line-number="2"><span class="kw">range</span>(x) <span class="co"># note this returns a vector c(minimum, maximum)</span></a></code></pre></div>
<pre><code>## [1]   1 100</code></pre>
</div>
<div id="interquartile-range-iqr" class="section level5">
<h5><span class="header-section-number">3.2.2.2.4</span> Interquartile Range (IQR)</h5>
<p>The interquartile range of a set is the middle 50% of the set, or the difference between the value associated with the 75th percentile and the 25th percentile. We can calculate this in a number of ways in <em>R</em>.</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb264-1" data-line-number="1"><span class="co"># First define a set of numbers.  Let&#39;s take 100 samples of the normal distribution with a </span></a>
<a class="sourceLine" id="cb264-2" data-line-number="2"><span class="co"># mean of 0 and a standard deviation of 1.</span></a>
<a class="sourceLine" id="cb264-3" data-line-number="3">x &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>) <span class="co"># Note the defaults for rnorm are the mean and standard deviation as listed above.</span></a>
<a class="sourceLine" id="cb264-4" data-line-number="4"></a>
<a class="sourceLine" id="cb264-5" data-line-number="5"><span class="co"># If you simply want the interquartile range, this function provides it:</span></a>
<a class="sourceLine" id="cb264-6" data-line-number="6"><span class="kw">IQR</span>(x)</a></code></pre></div>
<pre><code>## [1] 1.329045</code></pre>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb266-1" data-line-number="1"><span class="co"># If you want to see the quartiles explicitly, you can use quantile:</span></a>
<a class="sourceLine" id="cb266-2" data-line-number="2"><span class="kw">quantile</span>(x)</a></code></pre></div>
<pre><code>##           0%          25%          50%          75%         100% 
## -1.661199569 -0.720687045  0.002908299  0.608357605  2.933176036</code></pre>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb268-1" data-line-number="1"><span class="co"># You could do this and retype in the numbers explicitly, but that is not robust to </span></a>
<a class="sourceLine" id="cb268-2" data-line-number="2"><span class="co"># varying data sets. Understanding the output of quantile() is helpful.  We can see this </span></a>
<a class="sourceLine" id="cb268-3" data-line-number="3"><span class="co"># by saving the output</span></a>
<a class="sourceLine" id="cb268-4" data-line-number="4">myQuantile &lt;-<span class="st"> </span><span class="kw">quantile</span>(x)</a>
<a class="sourceLine" id="cb268-5" data-line-number="5"><span class="co"># You can see what myQuantile is by looking at its type (note, it&#39;s a double)</span></a>
<a class="sourceLine" id="cb268-6" data-line-number="6"><span class="kw">typeof</span>(myQuantile)</a></code></pre></div>
<pre><code>## [1] &quot;double&quot;</code></pre>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" data-line-number="1"><span class="co"># If you noted in the output that as opposed to what happens when you output a normal </span></a>
<a class="sourceLine" id="cb270-2" data-line-number="2"><span class="co"># vector, you had associated names, you can see these names as follows</span></a>
<a class="sourceLine" id="cb270-3" data-line-number="3"><span class="kw">names</span>(myQuantile)</a></code></pre></div>
<pre><code>## [1] &quot;0%&quot;   &quot;25%&quot;  &quot;50%&quot;  &quot;75%&quot;  &quot;100%&quot;</code></pre>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb272-1" data-line-number="1"><span class="co"># But, with this knowledge, you can call the specific indices you want (recall, R indexes vectors starting at 1!!!)</span></a>
<a class="sourceLine" id="cb272-2" data-line-number="2">myQuantile[<span class="dv">4</span>]</a></code></pre></div>
<pre><code>##       75% 
## 0.6083576</code></pre>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb274-1" data-line-number="1">myQuantile[<span class="dv">2</span>]</a></code></pre></div>
<pre><code>##       25% 
## -0.720687</code></pre>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb276-1" data-line-number="1"><span class="co"># You could then subtract the two</span></a>
<a class="sourceLine" id="cb276-2" data-line-number="2">myQuantile[<span class="dv">4</span>] <span class="op">-</span><span class="st"> </span>myQuantile[<span class="dv">2</span>] <span class="co"># note this preserves the names of the first result (annoying and inaccurate in this case)</span></a></code></pre></div>
<pre><code>##      75% 
## 1.329045</code></pre>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb278-1" data-line-number="1"><span class="co"># We can see that the two methods produce the same result:</span></a>
<a class="sourceLine" id="cb278-2" data-line-number="2"><span class="kw">IQR</span>(x) <span class="op">==</span><span class="st"> </span>myQuantile[<span class="dv">4</span>] <span class="op">-</span><span class="st"> </span>myQuantile[<span class="dv">2</span>]</a></code></pre></div>
<pre><code>##  75% 
## TRUE</code></pre>
</div>
</div>
<div id="standard-plots" class="section level4">
<h4><span class="header-section-number">3.2.2.3</span> Standard Plots</h4>
<p>This section assumes one is somewhat familiar with <code>ggplot()</code>. If not, please refer to the introduction to <em>R</em> chapter.</p>
<div id="boxplot" class="section level5">
<h5><span class="header-section-number">3.2.2.3.1</span> Boxplot</h5>
<p>A boxplot, or sometimes a box and whisker plot, shows dispersion of data according to its median, 75th and 25th percentiles (IQR) (which form the box), plus &quot;whiskers that extend to 1.5 * IQR beyond the 25th and 75th percentiles and then any outliers. This picture from wikipedia shows it very well:</p>
<div class="figure">
<img src="https://upload.wikimedia.org/wikipedia/commons/1/1a/Boxplot_vs_PDF.svg" alt="Boxplot Description From  Wikipedia " />
<p class="caption">Boxplot Description From <a href = "https://en.wikipedia.org/wiki/Interquartile_range"> Wikipedia </a></p>
</div>
<p>To plot a boxplot in R, use <code>geom_boxplot()</code> as described below:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb280-1" data-line-number="1"><span class="kw">library</span>(ggplot2) <span class="co"># We will use ggplot for all graphing </span></a>
<a class="sourceLine" id="cb280-2" data-line-number="2"></a>
<a class="sourceLine" id="cb280-3" data-line-number="3"><span class="co"># This plot uses mtcars and shows the dispersion of miles per gallon across all observations</span></a>
<a class="sourceLine" id="cb280-4" data-line-number="4"><span class="co"># Note, since we consolidated all of our observations into a single category, </span></a>
<a class="sourceLine" id="cb280-5" data-line-number="5"><span class="co"># we have no need to have an x axis.</span></a>
<a class="sourceLine" id="cb280-6" data-line-number="6"><span class="kw">ggplot</span>(<span class="dt">data =</span> mtcars) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="st">&#39;&#39;</span>, <span class="dt">y =</span> mpg))</a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Often we want to understand the variability by some other explanatory variable, in this case we can assess by the number of cylinders in a car</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb281-1" data-line-number="1"><span class="co"># This plot uses mtcars and shows the dispersion of miles per gallon across all observations</span></a>
<a class="sourceLine" id="cb281-2" data-line-number="2"><span class="co"># Note that in mtcars$cyl, the number of cylinders is numeric, but geom_boxplot will fail </span></a>
<a class="sourceLine" id="cb281-3" data-line-number="3"><span class="co"># with this input as an x, it needs a factor</span></a>
<a class="sourceLine" id="cb281-4" data-line-number="4"><span class="kw">ggplot</span>(<span class="dt">data =</span> mtcars) <span class="op">+</span><span class="st"> </span><span class="kw">geom_boxplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">as.factor</span>(cyl), <span class="dt">y =</span> mpg)) </a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
<div id="histograms-density-plots" class="section level5">
<h5><span class="header-section-number">3.2.2.3.2</span> Histograms &amp; Density Plots</h5>
<p>Histograms and density plots are useful to understanding how data is distributed across a variable (i.e., how frequently it occurs). We can plot these by using <code>geom_histogram()</code> and <code>geom_density()</code> respectively.</p>
<p>Histogram:</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb282-1" data-line-number="1"><span class="co"># Note you have many different options with geom_histogram such as binwidth.  I recommend </span></a>
<a class="sourceLine" id="cb282-2" data-line-number="2"><span class="co"># you spend some time playing with the options and understand what is occurring</span></a>
<a class="sourceLine" id="cb282-3" data-line-number="3"><span class="kw">ggplot</span>(mtcars) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mpg)) </a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb284-1" data-line-number="1"><span class="co"># You can also facet this, perhaps by cylinder</span></a>
<a class="sourceLine" id="cb284-2" data-line-number="2"><span class="kw">ggplot</span>(mtcars) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mpg)) <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(<span class="op">~</span>cyl)</a></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Density plots</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb286-1" data-line-number="1"><span class="kw">ggplot</span>(mtcars) <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mpg)) </a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Often it is nice to look at density plots overlayed on each other across some aesthetic (e.g., cylinders)</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb287-1" data-line-number="1"><span class="co"># note that aesthetics often do not work with numeric values, it&#39;s often better to term them a factor</span></a>
<a class="sourceLine" id="cb287-2" data-line-number="2"><span class="kw">ggplot</span>(mtcars) <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">x =</span> mpg, <span class="dt">color =</span> <span class="kw">as.factor</span>(cyl))) </a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
<div id="bar-or-column-charts" class="section level5">
<h5><span class="header-section-number">3.2.2.3.3</span> Bar or Column Charts</h5>
<p>Sometimes we want to represent counts or means or other statistics for some set of data, <code>geom_col()</code> and <code>geom_bar()</code> both allow us to do this. This is also a good exercise in grouping and summarizing data.</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb288-1" data-line-number="1">myData &lt;-<span class="st"> </span>mtcars <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb288-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(cyl) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb288-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Mean.MPG =</span> <span class="kw">mean</span>(mpg), <span class="dt">Number =</span> <span class="kw">n</span>()) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb288-4" data-line-number="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">cyl =</span> <span class="kw">as.factor</span>(cyl))</a>
<a class="sourceLine" id="cb288-5" data-line-number="5"><span class="co"># Note this gives us a new data frame that makes cyl a factor and give us the mean miles </span></a>
<a class="sourceLine" id="cb288-6" data-line-number="6"><span class="co"># per gallon for each sized engine and the number of observations for each engine size.</span></a>
<a class="sourceLine" id="cb288-7" data-line-number="7">myData </a></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   cyl   Mean.MPG Number
## * &lt;fct&gt;    &lt;dbl&gt;  &lt;int&gt;
## 1 4         26.7     11
## 2 6         19.7      7
## 3 8         15.1     14</code></pre>
<p>The column plot shows the mean miles per gallon.</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb290-1" data-line-number="1"><span class="kw">ggplot</span>(myData) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb290-2" data-line-number="2"><span class="st">    </span><span class="kw">geom_col</span>(<span class="kw">aes</span>(<span class="dt">x =</span> cyl, <span class="dt">y =</span> Mean.MPG)) <span class="op">+</span><span class="st"> </span><span class="co"># This gives us a column chart with cylinders on the x axis and miles per gallon on the y</span></a>
<a class="sourceLine" id="cb290-3" data-line-number="3"><span class="st">    </span><span class="kw">xlab</span>(<span class="st">&#39;Cylinders&#39;</span>) <span class="op">+</span><span class="st"> </span><span class="co"># It&#39;s a good idea to label your axes usefully</span></a>
<a class="sourceLine" id="cb290-4" data-line-number="4"><span class="st">    </span><span class="kw">ylab</span>(<span class="st">&#39;Mean Miles Per Gallon&#39;</span>)</a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>This bar plot shows</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb291-1" data-line-number="1"><span class="kw">ggplot</span>(myData) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="kw">aes</span>(<span class="dt">x =</span> cyl, <span class="dt">y =</span> Number), <span class="dt">stat =</span> <span class="st">&#39;identity&#39;</span>) </a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>We can also turn this into a pie chart by changing coordinates:</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb292-1" data-line-number="1"><span class="kw">ggplot</span>(myData) <span class="op">+</span><span class="st"> </span><span class="kw">geom_bar</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="st">&#39;&#39;</span>, <span class="dt">y =</span> Number, <span class="dt">fill =</span> cyl), <span class="dt">stat =</span> <span class="st">&#39;identity&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb292-2" data-line-number="2"><span class="st">    </span><span class="kw">coord_polar</span>(<span class="st">&#39;y&#39;</span>, <span class="dt">start =</span> <span class="dv">0</span>)</a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
</div>
</div>
<div id="understanding-calculating-and-plotting-distributions" class="section level4">
<h4><span class="header-section-number">3.2.2.4</span> Understanding, Calculating, and Plotting Distributions</h4>
<p>Probability distributions are fundamental to statistics. In this section, we’ll cover three things:</p>
<ol style="list-style-type: decimal">
<li>How <em>R</em> produces standard probability distributions.</li>
<li>How <em>R</em> can be used to build an empirical distribution from a set of data.</li>
<li>How <em>R</em> can be used to plot any probability distribution.</li>
</ol>
<div id="standard-probability-distributions" class="section level5">
<h5><span class="header-section-number">3.2.2.4.1</span> Standard Probability Distributions</h5>
<p>It is worth reviewing probability theory and probability distributions before beginning. Please see the resources above. Additionally:</p>
<ul>
<li>This <a href = "http://www.math.wm.edu/~leemis/chart/UDR/UDR.html" > link from William and Mary </a> is really cool. It shows the linkage of all univariate probability distributions!</li>
<li>This <a href = "https://www.stat.umn.edu/geyer/old/5101/rlook.html" > link from the University of Minnesota </a> is very useful. It shows all the basic random variable functions in <em>R</em>. I’ll only show a few so as not to be redundant.</li>
</ul>
<p>First, let’s recall the normal (or Gaussian) <a href = "https://en.wikipedia.org/wiki/Gaussian_function" > distribution </a>. This (or its approximation) is likely the most commonly used distribution in all of statistics.</p>
<div class="figure">
<img src="https://upload.wikimedia.org/wikipedia/commons/7/74/Normal_Distribution_PDF.svg" alt=" Wikipedia Depiction of the Normal Curve " />
<p class="caption"><a href = "https://en.wikipedia.org/wiki/Gaussian_function"> Wikipedia Depiction of the Normal Curve </a></p>
</div>
<p><em>R</em> has built in functions to get a random number from this distribution, <code>rnorm()</code>, which stands for random normal. It works as follows:</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb293-1" data-line-number="1"><span class="co">#rnorm(n, mean, sd) where n is the number of random numbers desired, mean is the mean </span></a>
<a class="sourceLine" id="cb293-2" data-line-number="2"><span class="co"># for your distribution, and sd is the standard deviation</span></a>
<a class="sourceLine" id="cb293-3" data-line-number="3"><span class="kw">rnorm</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 2.803058</code></pre>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb295-1" data-line-number="1"><span class="co"># note that it is random</span></a>
<a class="sourceLine" id="cb295-2" data-line-number="2"><span class="kw">rnorm</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.1174497</code></pre>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb297-1" data-line-number="1"><span class="co"># Note that if you ask for a vector, it will return N independent, identically </span></a>
<a class="sourceLine" id="cb297-2" data-line-number="2"><span class="co"># distributed values</span></a>
<a class="sourceLine" id="cb297-3" data-line-number="3"><span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dv">0</span>, <span class="dv">1</span>)</a></code></pre></div>
<pre><code>##  [1]  0.05649155  0.26344133  0.43058039 -0.20057846 -1.03925039 -1.20096107
##  [7] -0.47360459  0.79003676 -0.15714316 -0.77605794</code></pre>
<p>As a side note, the <code>set.seed()</code> command is useful if you want to set the random number generator seed for <em>R</em> if you’re concerned about replicability. As a side note, <em>R</em>, like nearly every (or perhaps all) other programming languages actually generates pseudorandom numbers. See the documentation <a href = "https://www.rdocumentation.org/packages/gsl/versions/2.1-6/topics/Rng" > here </a> if you’re really concerned about it. Back to <code>set.seed()</code>:</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb299-1" data-line-number="1"><span class="co"># recall that rnorm() returns a random number, and invoking it twice will almost </span></a>
<a class="sourceLine" id="cb299-2" data-line-number="2"><span class="co"># assuredly return two different numbers.</span></a>
<a class="sourceLine" id="cb299-3" data-line-number="3"><span class="kw">rnorm</span>(<span class="dv">1</span>) <span class="co"># recall that we can rely on the defaults for mean and standard deviation </span></a></code></pre></div>
<pre><code>## [1] 0.9734257</code></pre>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb301-1" data-line-number="1"><span class="co"># as 0 and 1 are OK for this</span></a>
<a class="sourceLine" id="cb301-2" data-line-number="2"><span class="kw">rnorm</span>(<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] -0.4674196</code></pre>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb303-1" data-line-number="1"><span class="co"># But, if we want to reproduce the same number every time **randomly** we can set the seed</span></a>
<a class="sourceLine" id="cb303-2" data-line-number="2"><span class="kw">set.seed</span>(<span class="dv">173</span>)</a>
<a class="sourceLine" id="cb303-3" data-line-number="3"><span class="kw">rnorm</span>(<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 1.053903</code></pre>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb305-1" data-line-number="1"><span class="co"># If we do it again, we&#39;ll get the same result!!!</span></a>
<a class="sourceLine" id="cb305-2" data-line-number="2"><span class="kw">set.seed</span>(<span class="dv">173</span>)</a>
<a class="sourceLine" id="cb305-3" data-line-number="3"><span class="kw">rnorm</span>(<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 1.053903</code></pre>
<p>Now that we can create a random number or set of numbers from the normal distribution, we may ask ourselves other things, like, given a distribution, what’s the probability that I’ll randomly select a number in a given range. <em>R</em>, conveniently provides us this with the <code>pnorm()</code> function. It works as follows:</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb307-1" data-line-number="1"><span class="co"># The syntax is: pnorm(q, mean, standard deviation)</span></a>
<a class="sourceLine" id="cb307-2" data-line-number="2"><span class="co"># This returns P(X &lt;= q) where X ~ N(mean, standard deviation)</span></a>
<a class="sourceLine" id="cb307-3" data-line-number="3"><span class="co"># Recall the normal distribution is symmetric about its mean, so you have a 50% chance of </span></a>
<a class="sourceLine" id="cb307-4" data-line-number="4"><span class="co"># seeing a value less than the mean.</span></a>
<a class="sourceLine" id="cb307-5" data-line-number="5"><span class="kw">pnorm</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.5</code></pre>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb309-1" data-line-number="1"><span class="co"># To test it a little, let&#39;s vary the parameters</span></a>
<a class="sourceLine" id="cb309-2" data-line-number="2"><span class="kw">pnorm</span>(<span class="dv">10</span>, <span class="dv">10</span>, <span class="dv">5</span>) <span class="co"># note that this should return .5</span></a></code></pre></div>
<pre><code>## [1] 0.5</code></pre>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb311-1" data-line-number="1"><span class="co"># And we know that we should get some number smaller than .5 if we choose a value less than the mean</span></a>
<a class="sourceLine" id="cb311-2" data-line-number="2"><span class="kw">pnorm</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.1586553</code></pre>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb313-1" data-line-number="1"><span class="co"># Similarly we should see some number that is higher than .5 if we choose a value greater than the mean</span></a>
<a class="sourceLine" id="cb313-2" data-line-number="2"><span class="kw">pnorm</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 0.8413447</code></pre>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb315-1" data-line-number="1"><span class="co"># We can of course, find the probability that a number is between two values by taking the </span></a>
<a class="sourceLine" id="cb315-2" data-line-number="2"><span class="co"># differences, for example, the probability that a number drawn from N(0, 1) is between -.5 </span></a>
<a class="sourceLine" id="cb315-3" data-line-number="3"><span class="co"># and .6 is calculated as:</span></a>
<a class="sourceLine" id="cb315-4" data-line-number="4"><span class="kw">pnorm</span>(.<span class="dv">6</span>) <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="op">-</span>.<span class="dv">5</span>)</a></code></pre></div>
<pre><code>## [1] 0.4172093</code></pre>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb317-1" data-line-number="1"><span class="co"># Note, up until now, we have been operating with a default argument, lower.tail = TRUE</span></a>
<a class="sourceLine" id="cb317-2" data-line-number="2"><span class="co"># This argument makes it so that we calculate P(X &lt;= q).  If we switch it to false, we&#39;ll </span></a>
<a class="sourceLine" id="cb317-3" data-line-number="3"><span class="co"># calculate the inverse, P(X &gt;= q). For example: we can say what is the probability that </span></a>
<a class="sourceLine" id="cb317-4" data-line-number="4"><span class="co"># a number randomly drawn from the standard normal is greater than 2:</span></a>
<a class="sourceLine" id="cb317-5" data-line-number="5"><span class="kw">pnorm</span>(<span class="dv">2</span>, <span class="dt">lower.tail =</span> F)</a></code></pre></div>
<pre><code>## [1] 0.02275013</code></pre>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb319-1" data-line-number="1"><span class="co"># We could, of course be mathy and calculate this as 1 - P(X &lt;= 2), X~N(0,1)</span></a>
<a class="sourceLine" id="cb319-2" data-line-number="2"><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="dv">2</span>) <span class="co"># Fortunately, this gives us the same result (which it should!!).</span></a></code></pre></div>
<pre><code>## [1] 0.02275013</code></pre>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb321-1" data-line-number="1"><span class="co"># Finally, pnorm has another argument, log.p = FALSE.  If you opt for this to be true, </span></a>
<a class="sourceLine" id="cb321-2" data-line-number="2"><span class="co"># it will return the log of the probability.  This can be useful, </span></a>
<a class="sourceLine" id="cb321-3" data-line-number="3"><span class="co"># see: https://en.wikipedia.org/wiki/Log_probability but I rarely, if ever do this.</span></a>
<a class="sourceLine" id="cb321-4" data-line-number="4"><span class="co"># See for example what happens when we change the flag:</span></a>
<a class="sourceLine" id="cb321-5" data-line-number="5"><span class="kw">pnorm</span>(<span class="dv">0</span>, <span class="dt">log.p =</span> T)</a></code></pre></div>
<pre><code>## [1] -0.6931472</code></pre>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb323-1" data-line-number="1"><span class="co"># This returns the same as:</span></a>
<a class="sourceLine" id="cb323-2" data-line-number="2"><span class="kw">log</span>(<span class="kw">pnorm</span>(<span class="dv">0</span>))</a></code></pre></div>
<pre><code>## [1] -0.6931472</code></pre>
<p><code>pnorm()</code> returns the “probability” (i.e. the cumulative distribution function). Sometimes we may want its inverse, that is, for a given percentile (or quantile), we want to know the value. We get this with the <code>qnorm()</code> function. Note that it has all of the same arguments as pnorm.</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb325-1" data-line-number="1"><span class="co"># We know that the normal distribution is symmetric, so the 50th percentile should be at </span></a>
<a class="sourceLine" id="cb325-2" data-line-number="2"><span class="co"># the mean and we can validate that here:</span></a>
<a class="sourceLine" id="cb325-3" data-line-number="3"><span class="kw">qnorm</span>(.<span class="dv">5</span>) <span class="co"># This returns 0 as we have a mean of 0</span></a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb327-1" data-line-number="1"><span class="co"># We know that you can never get a 100 percentile as the normal distribution doesn&#39;t have </span></a>
<a class="sourceLine" id="cb327-2" data-line-number="2"><span class="co"># an upper limit</span></a>
<a class="sourceLine" id="cb327-3" data-line-number="3"><span class="kw">qnorm</span>(<span class="dv">1</span>) <span class="co"># R returns infinite, though, the most appropriate thing to say here, is the limit </span></a></code></pre></div>
<pre><code>## [1] Inf</code></pre>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb329-1" data-line-number="1"><span class="co"># of qnorm(x) as x goes to 1 is infinity!  Let&#39;s not be pedantic though.</span></a>
<a class="sourceLine" id="cb329-2" data-line-number="2"><span class="co"># Similarly, we get an inverse result for a 0th percentile</span></a>
<a class="sourceLine" id="cb329-3" data-line-number="3"><span class="kw">qnorm</span>(<span class="dv">0</span>)</a></code></pre></div>
<pre><code>## [1] -Inf</code></pre>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb331-1" data-line-number="1"><span class="co"># You can get standard quartiles in a similar fashion:</span></a>
<a class="sourceLine" id="cb331-2" data-line-number="2"><span class="kw">qnorm</span>(.<span class="dv">25</span>)</a></code></pre></div>
<pre><code>## [1] -0.6744898</code></pre>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb333-1" data-line-number="1"><span class="kw">qnorm</span>(.<span class="dv">75</span>)</a></code></pre></div>
<pre><code>## [1] 0.6744898</code></pre>
<p>Finally, sometimes we want the “density” (i.e., the values for the probability distribution function) or, colloquially, the y value for a given x on the distribution curve. We get this with <code>dnorm()</code>:</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb335-1" data-line-number="1"><span class="co">#dnorm(x value, mean, standard deviation)</span></a>
<a class="sourceLine" id="cb335-2" data-line-number="2"><span class="kw">dnorm</span>(<span class="dv">0</span>)</a></code></pre></div>
<pre><code>## [1] 0.3989423</code></pre>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb337-1" data-line-number="1"><span class="co"># This implies that when one plots the height of the standard normal function, at 0, it </span></a>
<a class="sourceLine" id="cb337-2" data-line-number="2"><span class="co"># would be ~.39 (note, this does NOT mean you have a 40% chance of randomly selecting a </span></a>
<a class="sourceLine" id="cb337-3" data-line-number="3"><span class="co"># 0 out of the standard normal). There is no lower.tail argument as that is not meaningful </span></a>
<a class="sourceLine" id="cb337-4" data-line-number="4"><span class="co"># for this function, but the log argument defaults to FALSE</span></a></code></pre></div>
<p><em>R</em> has a similar standard set up of:</p>
<ul>
<li>r[distribution handle] for random number from a distribution.</li>
<li>d[distribution handle] for density of a number from a distribution.</li>
<li>p[distribution handle] for the cumulative distribution function.</li>
<li>q[distribution handle] for the inverse cumulative distribution function.</li>
</ul>
<p>I recommend you look up your favorite distribution and try it out. <font color = 'red'> Be careful, </font> make sure you read the documentation!!! <em>R</em> (and any computer language) will return exactly what you ask of it. Make sure you know what the parameters are asking for. For example, if you assume that <em>R</em> wants the variance instead of the standard deviation, you will get results for a distribution with a much larger spread than you intended!</p>
<p>Finally, if base <em>R</em> does not have your preferred distribution, I recommend Googling it. Many packages provide additional distributions.</p>
<p>Let’s briefly look at a discrete distribution and then continue on. Recall the <a href = "https://en.wikipedia.org/wiki/Binomial_distribution" > binomial distribution </a> which returns the number of successful results out of N trials where you have a probability P of success (you can only succeed or fail in this distribution). <code>*binom()</code> (where * is r, d, p, or q) is what we want.</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb338-1" data-line-number="1"><span class="co"># Please look at the documentation for the syntax, type the command: ?rbinom to view it</span></a>
<a class="sourceLine" id="cb338-2" data-line-number="2"><span class="co"># in RStudio. Let&#39;s look at 10 random variables of 4 trials where we have a 50% chance </span></a>
<a class="sourceLine" id="cb338-3" data-line-number="3"><span class="co"># of succeeding</span></a>
<a class="sourceLine" id="cb338-4" data-line-number="4"><span class="kw">rbinom</span>(<span class="dv">16</span>, <span class="dv">4</span>, <span class="fl">.5</span>)</a></code></pre></div>
<pre><code>##  [1] 2 3 4 2 2 2 2 2 1 2 2 1 4 1 3 1</code></pre>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb340-1" data-line-number="1"><span class="co"># This likely makes sense, we could analytically think of the probabilities (think of your</span></a>
<a class="sourceLine" id="cb340-2" data-line-number="2"><span class="co"># odds of flipping four fair coins), but we can take this to a few edge cases to test the</span></a>
<a class="sourceLine" id="cb340-3" data-line-number="3"><span class="co"># results: Consider a guranteed success (i.e., probability of 1)</span></a>
<a class="sourceLine" id="cb340-4" data-line-number="4"><span class="kw">rbinom</span>(<span class="dv">10</span>, <span class="dv">4</span>, <span class="dv">1</span>) <span class="co"># This will return all 4s as we can only win</span></a></code></pre></div>
<pre><code>##  [1] 4 4 4 4 4 4 4 4 4 4</code></pre>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb342-1" data-line-number="1"><span class="co"># Consider the opposite, it&#39;s impossible to win</span></a>
<a class="sourceLine" id="cb342-2" data-line-number="2"><span class="kw">rbinom</span>(<span class="dv">10</span>, <span class="dv">4</span>, <span class="dv">0</span>)</a></code></pre></div>
<pre><code>##  [1] 0 0 0 0 0 0 0 0 0 0</code></pre>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb344-1" data-line-number="1"><span class="co"># Let&#39;s now consider the probabilities that we&#39;ll have n or fewer successes in 4 trials of </span></a>
<a class="sourceLine" id="cb344-2" data-line-number="2"><span class="co"># a 50-50 experiment where n is 0, 1, 2, 3, or 4</span></a>
<a class="sourceLine" id="cb344-3" data-line-number="3"><span class="kw">pbinom</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="fl">.5</span>)</a></code></pre></div>
<pre><code>## [1] 0.0625 0.3125 0.6875 0.9375 1.0000</code></pre>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb346-1" data-line-number="1"><span class="co"># You can get the probability of getting exactly n successes as we did above.  For example, </span></a>
<a class="sourceLine" id="cb346-2" data-line-number="2"><span class="co"># the probability of seeing exactly 3 successes is:</span></a>
<a class="sourceLine" id="cb346-3" data-line-number="3"><span class="kw">pbinom</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="fl">.5</span>) <span class="op">-</span><span class="st"> </span><span class="kw">pbinom</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="fl">.5</span>)</a></code></pre></div>
<pre><code>## [1] 0.25</code></pre>
</div>
<div id="build-empirical-distributions" class="section level5">
<h5><span class="header-section-number">3.2.2.4.2</span> Build Empirical Distributions</h5>
<p>Sometimes, we have a dataset and we want to build our own distribution out of it (for any number of reasons). <em>R</em> has a few functions that help us replicate the above type functions.</p>
<p>First, let’s build a data set:</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb348-1" data-line-number="1"><span class="co"># We&#39;ll build a dataset that is a sample of 100 random variables of two normal </span></a>
<a class="sourceLine" id="cb348-2" data-line-number="2"><span class="co"># distributions with differing means and standard deviations</span></a>
<a class="sourceLine" id="cb348-3" data-line-number="3">myData &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">20</span>, <span class="dv">3</span>), <span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dv">5</span>, <span class="dv">5</span>)) </a>
<a class="sourceLine" id="cb348-4" data-line-number="4"><span class="co"># note we can combine two or more vectors with the c() command</span></a>
<a class="sourceLine" id="cb348-5" data-line-number="5"><span class="co"># Let&#39;s look at the data to get an idea of what we&#39;re working with</span></a>
<a class="sourceLine" id="cb348-6" data-line-number="6"><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">x =</span> myData))</a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>We can draw a random sample (from this data set!) using the sample function.</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb349-1" data-line-number="1"><span class="co"># Note 1: This is not the same as a random sample from a probability distribution, this is # only sampling from the given data.</span></a>
<a class="sourceLine" id="cb349-2" data-line-number="2"><span class="co"># Note 2: Please see the documentation on sample using ?sample to read about your </span></a>
<a class="sourceLine" id="cb349-3" data-line-number="3"><span class="co"># arguments.  For example, the default is that replace is FALSE</span></a>
<a class="sourceLine" id="cb349-4" data-line-number="4"><span class="kw">sample</span>(myData, <span class="dv">5</span>)</a></code></pre></div>
<pre><code>## [1]  5.702567  4.645398  7.479771 20.364705 20.308881</code></pre>
<p>If we want to build a cumulative distribution function, we can use the command <code>ecdf()</code> (empirical cumulative distribution function). This then gives us a function similar to <code>p[distro]()</code>.</p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb351-1" data-line-number="1">myCDF &lt;-<span class="st"> </span><span class="kw">ecdf</span>(myData)</a>
<a class="sourceLine" id="cb351-2" data-line-number="2"><span class="co"># We can then use myCDF as a function. Note, it does not have the same optional arguments as p[distro]</span></a>
<a class="sourceLine" id="cb351-3" data-line-number="3"><span class="kw">myCDF</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">20</span>)</a></code></pre></div>
<pre><code>##  [1] 0.105 0.125 0.145 0.160 0.185 0.235 0.265 0.315 0.375 0.410 0.440 0.460
## [13] 0.475 0.505 0.520 0.545 0.560 0.605 0.660 0.730</code></pre>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb353-1" data-line-number="1"><span class="co"># if we want to plot this, we can make up data points and assess them with this function</span></a>
<a class="sourceLine" id="cb353-2" data-line-number="2">myX &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="kw">floor</span>(<span class="kw">min</span>(myData)), <span class="kw">ceiling</span>(<span class="kw">max</span>(myData)), <span class="dt">by =</span> <span class="fl">.01</span>) <span class="co"># Note here, we are nesting</span></a>
<a class="sourceLine" id="cb353-3" data-line-number="3"><span class="co"># functions, we are getting the minimum of myData, which is about -7.6 and taking the</span></a>
<a class="sourceLine" id="cb353-4" data-line-number="4"><span class="co"># floor, which rounds us down to -8, and doing a similar process for the maximum, then</span></a>
<a class="sourceLine" id="cb353-5" data-line-number="5"><span class="co"># building a vector that is a sequence from -8 to 27 by .01</span></a>
<a class="sourceLine" id="cb353-6" data-line-number="6">myY &lt;-<span class="st"> </span><span class="kw">myCDF</span>(myX) <span class="co"># we then calculate the cumulative distribution for each number in &#39;myX&#39; </span></a>
<a class="sourceLine" id="cb353-7" data-line-number="7"></a>
<a class="sourceLine" id="cb353-8" data-line-number="8"><span class="co"># Now we can plot each of the assessed points</span></a>
<a class="sourceLine" id="cb353-9" data-line-number="9"><span class="co"># Note the \n in the middle of the y label indicates a new line</span></a>
<a class="sourceLine" id="cb353-10" data-line-number="10"><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb353-11" data-line-number="11"><span class="st">    </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> myX, <span class="dt">y =</span> myY)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb353-12" data-line-number="12"><span class="st">    </span><span class="kw">xlab</span>(<span class="st">&#39;X Value&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb353-13" data-line-number="13"><span class="st">    </span><span class="kw">ylab</span>(<span class="st">&#39;Probability that a random variable drawn</span><span class="ch">\n</span><span class="st">from this distribution is less than or equal to X&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb353-14" data-line-number="14"><span class="st">    </span><span class="kw">ggtitle</span>(<span class="st">&#39;Example Empirical Cumulative Distribution Function&#39;</span>)</a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<p>Sometimes we want the inverse (i.e., the quantiles for a given data set). The <code>quantile()</code> function gives us this, though it does not return a function. You simply provide it the data set and the desired quantiles:</p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb354-1" data-line-number="1"><span class="co"># the defaults are to return 0%, 25%, 50%, 75%, and 100% (note that 0 &amp; 100 percentiles</span></a>
<a class="sourceLine" id="cb354-2" data-line-number="2"><span class="co"># are equivalent to the maximum and minimum values)  </span></a>
<a class="sourceLine" id="cb354-3" data-line-number="3"><span class="kw">quantile</span>(myData) </a></code></pre></div>
<pre><code>##        0%       25%       50%       75%      100% 
## -8.325318  6.178409 13.932411 20.314173 28.332020</code></pre>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb356-1" data-line-number="1"><span class="co"># If you want to return specific quantiles, you can pass a single value:</span></a>
<a class="sourceLine" id="cb356-2" data-line-number="2"><span class="kw">quantile</span>(myData, <span class="fl">.1</span>)</a></code></pre></div>
<pre><code>##       10% 
## 0.8716211</code></pre>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb358-1" data-line-number="1"><span class="co"># Or you can pass a vector of values:</span></a>
<a class="sourceLine" id="cb358-2" data-line-number="2"><span class="kw">quantile</span>(myData, <span class="kw">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">.1</span>))</a></code></pre></div>
<pre><code>##         0%        10%        20%        30%        40%        50%        60% 
## -8.3253183  0.8716211  5.2561141  7.6465339  9.8870812 13.9324113 17.9613913 
##        70%        80%        90%       100% 
## 19.6611832 20.9977018 22.8964485 28.3320200</code></pre>
<p>If we want to turn this into a distribution we can use, however, we can build a probability distribution function with the <code>density()</code> command:</p>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb360-1" data-line-number="1"><span class="co"># This outputs the density for a set of Xs (i.e. values) and their associated densities as</span></a>
<a class="sourceLine" id="cb360-2" data-line-number="2"><span class="co"># Y&#39;s. Note that this is not a data frame, it is a list</span></a>
<a class="sourceLine" id="cb360-3" data-line-number="3">myPDF &lt;-<span class="st"> </span><span class="kw">density</span>(myData)</a>
<a class="sourceLine" id="cb360-4" data-line-number="4">myPDF</a></code></pre></div>
<pre><code>## 
## Call:
##  density.default(x = myData)
## 
## Data: myData (200 obs.); Bandwidth &#39;bw&#39; = 2.626
## 
##        x                y            
##  Min.   :-16.20   Min.   :8.990e-06  
##  1st Qu.: -3.10   1st Qu.:1.849e-03  
##  Median : 10.00   Median :1.797e-02  
##  Mean   : 10.00   Mean   :1.906e-02  
##  3rd Qu.: 23.11   3rd Qu.:3.277e-02  
##  Max.   : 36.21   Max.   :5.153e-02</code></pre>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb362-1" data-line-number="1"><span class="co"># If we want to understand this object better, first note:</span></a>
<a class="sourceLine" id="cb362-2" data-line-number="2"><span class="co"># It is a list: </span></a>
<a class="sourceLine" id="cb362-3" data-line-number="3"><span class="kw">typeof</span>(myPDF)</a></code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb364-1" data-line-number="1"><span class="co"># With a specific class called &#39;density&quot;</span></a>
<a class="sourceLine" id="cb364-2" data-line-number="2"><span class="kw">class</span>(myPDF)</a></code></pre></div>
<pre><code>## [1] &quot;density&quot;</code></pre>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb366-1" data-line-number="1"><span class="co"># With 7 elements</span></a>
<a class="sourceLine" id="cb366-2" data-line-number="2"><span class="kw">summary</span>(myPDF)</a></code></pre></div>
<pre><code>##           Length Class  Mode     
## x         512    -none- numeric  
## y         512    -none- numeric  
## bw          1    -none- numeric  
## n           1    -none- numeric  
## call        2    -none- call     
## data.name   1    -none- character
## has.na      1    -none- logical</code></pre>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb368-1" data-line-number="1"><span class="co"># And note that it has a call that produces a nice summary when you call the object, the</span></a>
<a class="sourceLine" id="cb368-2" data-line-number="2"><span class="co"># function is called density.default</span></a>
<a class="sourceLine" id="cb368-3" data-line-number="3">myPDF<span class="op">$</span>call</a></code></pre></div>
<pre><code>## density.default(x = myData)</code></pre>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb370-1" data-line-number="1"><span class="co"># If we want to plot the Xs and Ys, we can&#39;t treat this as a data frame, but we can access</span></a>
<a class="sourceLine" id="cb370-2" data-line-number="2"><span class="co"># the set of Xs and Ys by calling them directly</span></a>
<a class="sourceLine" id="cb370-3" data-line-number="3"><span class="co"># Note, this produces the same thing as a geom_density plot as described above</span></a>
<a class="sourceLine" id="cb370-4" data-line-number="4"><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> myPDF<span class="op">$</span>x, <span class="dt">y =</span> myPDF<span class="op">$</span>y))</a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
</div>
<div id="probability-distribution-conclusions" class="section level5">
<h5><span class="header-section-number">3.2.2.4.3</span> Probability Distribution Conclusions</h5>
<p>You should now be able to generate random variables, calculate probabilities, and plot probability distributions in a number of ways. We specifically showed how to use the normal, binomial, and empirical distributions in <em>R</em>. I recommend you try to do this for other common distributions (e.g., the uniform, the student t, <span class="math inline">\(\chi^2\)</span>, etc.).</p>
<p>Finally, ensure you understand the distribution you are using. Many (perhaps most) have important parameters that are: 1) not necessarily intuitive, and 2) have specific meanings. Often, the parameters are defined in a certain way in <em>R</em> that may or may not be your favorite way of doing it (e.g., using the variance vs. the standard deviation).</p>
</div>
</div>
</div>
<div id="descriptive-statistics---problem-set" class="section level3">
<h3><span class="header-section-number">3.2.3</span> Descriptive Statistics - Problem Set</h3>
<ul>
<li>You can view the problem set here <a href = "/_Chapter3_ProblemSets/2-1_Descriptive_Statistics.html"> Descriptive Statistics Problem Set </a>.</li>
<li>For your convenience, <a href = "/_Chapter3_ProblemSets/2-1_Descriptive_Statistics.Rmd">here is the problem set as an R Markdown.</a></li>
<li>You can download the Ames Iowa data set here <a href = "/_Chapter3_ProblemSets/ames.csv"> Ames, Iowa Data Set </a>.</li>
<li>You can view the problem set solution <a href = "/_Chapter3_ProblemSets/2-1_Descriptive_Statistics_Answers.html"> here </a>.</li>
</ul>
</div>
</div>
<div id="statistical-concepts" class="section level2">
<h2><span class="header-section-number">3.3</span> Statistical Concepts</h2>
<div id="statistical-concepts---description" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Statistical Concepts - Description</h3>
<p>This section is a refresher for analysts on fundamental statistical concepts including the following:</p>
<ul>
<li>Statistical terminology.</li>
<li>Sampling distributions and the central limit theorem.</li>
</ul>
</div>
<div id="statistical-concepts---tutorial" class="section level3">
<h3><span class="header-section-number">3.3.2</span> Statistical Concepts - Tutorial</h3>
<div id="statistical-terminology." class="section level4">
<h4><span class="header-section-number">3.3.2.1</span> Statistical Terminology.</h4>
<p>When doing and discussing statistics, it is important to be precise in your use of language. Here are a few terms we will use:</p>
<div id="random-sample" class="section level5">
<h5><span class="header-section-number">3.3.2.1.1</span> Random Sample</h5>
<p>“A sample [i.e., a subset] that has been selected from the population in such a way that every possible sample has an equal probability of being selected.” (Montgomery, 2012, pg. 30).</p>
<p>There are many sampling techniques (see, e.g., <a href = 'https://www.khanacademy.org/math/statistics-probability/designing-studies#sampling-methods-stats'> Khan Academy Sampling </a>), however, for us, there are two important points:</p>
<ul>
<li>Many statistical tests assume a random sample. We need to ensure we know which tests assume what <em>and</em> if the data we are using can be assumed to be a reasonably random sample.</li>
<li>We are largely concerned with computer simulation. This means that we can generally look at the random variables we use. That stated, we must be careful when we are assessing results of a simulation, because we may not have independent results (we will have more discussion on this in a future chapter).</li>
<li>We must be deliberate when sampling from a population to consider whether we want <em>with</em> or <em>without</em> replacement.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>
<ul>
<li>With replacement means we allow for the possibility of selecting the same member of a set more than once when we sample.</li>
<li>Without replacement means we do not allow for the above possibility.</li>
<li>Drawing without replacement alters the underlying distribution from which we are sampling, thus negating the assumption that a sample is drawn from an independent, identically distributed population that is used in many statistical tests.</li>
<li>The default in <em>R</em> for <code>sample</code> and <code>sample_n</code> is to sample without replacement. Be aware of your choice.</li>
</ul></li>
</ul>
</div>
<div id="statistic" class="section level5">
<h5><span class="header-section-number">3.3.2.1.2</span> Statistic</h5>
<p>A statistic is “any function of the observations in a sample that does not contain unknown parameters” (Montgomery, 2012, pg. 31).</p>
<p>This is a precise way of saying a statistic is an unambiguous function of a sample. Common statistics are the (sample) mean, (sample) standard deviation, etc.</p>
<p>Note that statistics are often used to estimate the <em>parameter</em> of a population. The <em>parameter</em> of a population is a function of the entire population. For example, I work in an organization of ~150 people. Each of these people has an unambiguous age, and, if I were nosy enough, I could record all of the ages and get the mean for my organization (at that point in time). This is the true mean. Conversely, if I weren’t so nosy, or did not have the resources, I could randomly sample a subset of the organization and estimate the (true) mean with the statistic the (sample) mean. It will (almost assuredly) not be correct, but will likely be “close enough” for our purposes (we’ll make “close enough” more precise in a future section).</p>
<p>As an example, we can see this visually by plotting the mean of several samples of the normal distribution and comparing that to the true mean:</p>
<div class="sourceCode" id="cb371"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb371-1" data-line-number="1"><span class="co"># create a useful function that returns the mean of a sample of size X of the standard</span></a>
<a class="sourceLine" id="cb371-2" data-line-number="2"><span class="co"># normal distribution</span></a>
<a class="sourceLine" id="cb371-3" data-line-number="3">myFunc &lt;-<span class="st"> </span><span class="cf">function</span>(X){<span class="kw">return</span>(<span class="kw">mean</span>(<span class="kw">rnorm</span>(X)))}</a>
<a class="sourceLine" id="cb371-4" data-line-number="4"></a>
<a class="sourceLine" id="cb371-5" data-line-number="5"><span class="co"># Generate a vector of the mean of 10 random samples of 10 observations of the standard</span></a>
<a class="sourceLine" id="cb371-6" data-line-number="6"><span class="co"># normal. It is beyond the scope of this section to discuss the various apply functions in</span></a>
<a class="sourceLine" id="cb371-7" data-line-number="7"><span class="co"># R, but they are highly useful and I recommend learning about the apply functions.</span></a>
<a class="sourceLine" id="cb371-8" data-line-number="8">myMeans &lt;-<span class="st"> </span><span class="kw">sapply</span>(<span class="kw">rep</span>(<span class="dv">30</span>, <span class="dv">10</span>), myFunc)</a>
<a class="sourceLine" id="cb371-9" data-line-number="9"></a>
<a class="sourceLine" id="cb371-10" data-line-number="10"><span class="co"># Plot the results:</span></a>
<a class="sourceLine" id="cb371-11" data-line-number="11"><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb371-12" data-line-number="12"><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> myMeans, <span class="dt">y =</span> <span class="kw">rep</span>(<span class="dv">0</span>, <span class="dv">10</span>))) <span class="op">+</span><span class="st"> </span><span class="co"># Plot each point</span></a>
<a class="sourceLine" id="cb371-13" data-line-number="13"><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="dv">0</span>, <span class="dt">y =</span> <span class="dv">0</span>), <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">fill =</span> <span class="ot">NA</span>, <span class="dt">size =</span> <span class="dv">10</span>, <span class="dt">shape =</span> <span class="dv">3</span>) <span class="op">+</span><span class="st"> </span><span class="co"># Plot the parameter mean and make it distinct</span></a>
<a class="sourceLine" id="cb371-14" data-line-number="14"><span class="st">  </span><span class="kw">theme_minimal</span>() <span class="op">+</span><span class="st"> </span><span class="co"># I prefer a minimal background</span></a>
<a class="sourceLine" id="cb371-15" data-line-number="15"><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;Sample Means of 10 observations of the Standard Normal Distribution&#39;</span>) <span class="op">+</span><span class="st"> </span><span class="co"># Label our axes and title</span></a>
<a class="sourceLine" id="cb371-16" data-line-number="16"><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&#39;&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb371-17" data-line-number="17"><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&#39;Sample Means vs. the Mean Parameter</span><span class="ch">\n</span><span class="st">Standard Normal Distribution&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb371-18" data-line-number="18"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.y =</span> <span class="kw">element_blank</span>()) <span class="op">+</span><span class="st"> </span><span class="co"># The y axis is meaningless, so remove it</span></a>
<a class="sourceLine" id="cb371-19" data-line-number="19"><span class="st">  </span><span class="kw">xlim</span>(<span class="kw">c</span>(<span class="op">-</span><span class="fl">1.1</span><span class="op">*</span><span class="kw">max</span>(<span class="kw">abs</span>(myMeans)), <span class="fl">1.1</span><span class="op">*</span><span class="kw">max</span>(<span class="kw">abs</span>(myMeans)))) <span class="co"># Choose a symmetric x axis </span></a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
</div>
<div id="estimator" class="section level5">
<h5><span class="header-section-number">3.3.2.1.3</span> Estimator</h5>
<p>As discussed above, many (perhaps all) statistics are estimations of some true population parameter. An estimator is defined as:</p>
<p>“An estimator of an unknown parameter is a statistic that corresponds to that parameter. Note that a point estimator is a random variable.” (Montgomery, 2012, pg. 31). We can see this randomness in the plot above of the ten random samples and corresponding point estimates of the mean of the standard normal distribution.</p>
<p>Statisticians have done much work to identify the <em>best</em> estimators for various population parameters. In general, estimators should be:</p>
<ul>
<li><strong>Unbiased.</strong> That is, the expected value of the estimator should equal the parameter. You can read more about this <a href = "https://en.wikipedia.org/wiki/Bias_of_an_estimator">here</a>.</li>
<li><strong>Minimum Variance.</strong> The estimator should have variance that is smaller than any other possible estimator of that parameter. You can read more about this <a href = "https://en.wikipedia.org/wiki/Minimum-variance_unbiased_estimator">here</a>.</li>
</ul>
<p>There are many different ways to estimate a parameter</p>
</div>
<div id="degrees-of-freedom" class="section level5">
<h5><span class="header-section-number">3.3.2.1.4</span> Degrees of Freedom</h5>
<p>Related to the discussion of estimators is the concept of “degrees of freedom”. Degrees of freedom are the number of values in the calculation of a statistic that are free to vary. This is generally related to the sample size and the statistic(s) one is calculating. You can read more about degrees of freedom <a href = "https://en.wikipedia.org/wiki/Degrees_of_freedom_(statistics)">here</a>.</p>
<p>We’ll cover the calculation of degrees of freedom for specific instances (e.g., regression, ANOVA) as required.</p>
</div>
</div>
<div id="sampling-distribution" class="section level4">
<h4><span class="header-section-number">3.3.2.2</span> Sampling Distribution</h4>
<p>Finally, the concept of a sampling distribution is highly important in the understanding of statistics. <a href = "https://www.khanacademy.org/math/ap-statistics/sampling-distribution-ap">Khan Academy</a> has a good overview of the sampling distribution, so we will not repeat the entire discussion here. That stated, there are a few important things to note:</p>
<ul>
<li>Recall that a statistic is, in and of itself, a random variable.</li>
<li>This random variable has a probability distribution (i.e., the <em>sampling distribution</em>).</li>
<li>If the statistic is a <em>good</em> estimator, it has a mean centered on the value of the population parameter and minimal variance.</li>
<li>For a statistic with a well defined mean and standard deviation, the sampling distribution of that statistic converges on the normal distribution with a mean centered on the parameter value associated with that statistic as defined by the Central Limit Theorem.</li>
</ul>
<div id="central-limit-theorem" class="section level5">
<h5><span class="header-section-number">3.3.2.2.1</span> Central Limit Theorem</h5>
<p>The Central Limit Theorem is a highly important concept in statistics, particularly as it relates to sampling distributions. <a href = "https://www.khanacademy.org/math/ap-statistics/sampling-distribution-ap/sampling-distribution-mean/v/central-limit-theorem">Khan Academy</a> has a good overview of it that is worth watching.</p>
<p>It is sometimes useful to observe the central limit theorem in action. We can plot the sampling distribution for the mean of an arbitrary population using multiple sample sizes as an example. Let’s do that here:</p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb372-1" data-line-number="1"><span class="co"># Let&#39;s look at the population as described by the exponential distribution with lambda = 2</span></a>
<a class="sourceLine" id="cb372-2" data-line-number="2"><span class="co"># Recall what this distribution looks like</span></a>
<a class="sourceLine" id="cb372-3" data-line-number="3"></a>
<a class="sourceLine" id="cb372-4" data-line-number="4"><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb372-5" data-line-number="5"><span class="st">    </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">rexp</span>(<span class="dv">100000</span>, <span class="dt">rate =</span> <span class="dv">2</span>))) <span class="op">+</span><span class="st"> </span><span class="co"># We&#39;ll take a large random sample using rexp() (i.e. random exponential)</span></a>
<a class="sourceLine" id="cb372-6" data-line-number="6"><span class="st">    </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">1</span><span class="op">/</span><span class="dv">2</span>, <span class="dt">lty =</span> <span class="dv">2</span>) <span class="op">+</span><span class="st"> </span><span class="co"># We&#39;ll plot the mean which is defined as 1/lambda</span></a>
<a class="sourceLine" id="cb372-7" data-line-number="7"><span class="st">    </span><span class="kw">ggtitle</span>(<span class="st">&#39;Exponential Distribution - Lambda = 2&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb372-8" data-line-number="8"><span class="st">    </span><span class="kw">xlab</span>(<span class="st">&#39;X&#39;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&#39;Density&#39;</span>)</a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-34-1.png" width="672" /></p>
<div class="sourceCode" id="cb373"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb373-1" data-line-number="1"><span class="co"># Now, let&#39;s look at the sampling distribution of the mean of the random exponential for a</span></a>
<a class="sourceLine" id="cb373-2" data-line-number="2"><span class="co"># given sample size. </span></a>
<a class="sourceLine" id="cb373-3" data-line-number="3"><span class="co"># First, let&#39;s write a function that returns the mean of a sample of a the variable</span></a>
<a class="sourceLine" id="cb373-4" data-line-number="4"><span class="co"># note, writing functions is beyond the scope of this section.  Just understand that what</span></a>
<a class="sourceLine" id="cb373-5" data-line-number="5"><span class="co"># this function does is return the mean of a random sample of size `Sample.Size` from the</span></a>
<a class="sourceLine" id="cb373-6" data-line-number="6"><span class="co"># population described by the random exponential with lambda = 2</span></a>
<a class="sourceLine" id="cb373-7" data-line-number="7">mySampleMeanFunction &lt;-<span class="st"> </span><span class="cf">function</span>(Sample.Size){<span class="kw">mean</span>(<span class="kw">rexp</span>(Sample.Size, <span class="dt">rate =</span> <span class="dv">2</span>))}</a>
<a class="sourceLine" id="cb373-8" data-line-number="8"></a>
<a class="sourceLine" id="cb373-9" data-line-number="9"><span class="co">## Second, let&#39;s build a data frame that contains many observations of this mean for</span></a>
<a class="sourceLine" id="cb373-10" data-line-number="10"><span class="co"># varying sample sizes</span></a>
<a class="sourceLine" id="cb373-11" data-line-number="11">mySampleDF &lt;-<span class="st"> </span><span class="kw">data.frame</span>() <span class="co">#define an empty data frame</span></a>
<a class="sourceLine" id="cb373-12" data-line-number="12"></a>
<a class="sourceLine" id="cb373-13" data-line-number="13"><span class="co"># This builds a data frame of 1000 sample mean observations with varying sample sizes </span></a>
<a class="sourceLine" id="cb373-14" data-line-number="14"><span class="co"># (5, 10, ... 35)</span></a>
<a class="sourceLine" id="cb373-15" data-line-number="15"><span class="cf">for</span>(n <span class="cf">in</span> <span class="kw">seq</span>(<span class="dv">5</span>, <span class="dv">35</span>, <span class="dt">by =</span> <span class="dv">5</span>)){</a>
<a class="sourceLine" id="cb373-16" data-line-number="16">  mySampleMeanObservations &lt;-<span class="st"> </span><span class="kw">sapply</span>(<span class="kw">rep</span>(n, <span class="dv">1000</span>), mySampleMeanFunction)</a>
<a class="sourceLine" id="cb373-17" data-line-number="17">  mySampleDF &lt;-<span class="st"> </span><span class="kw">rbind</span>(mySampleDF, <span class="kw">data.frame</span>(<span class="dt">SampleObservations =</span> mySampleMeanObservations, <span class="dt">SampleSize =</span> n))</a>
<a class="sourceLine" id="cb373-18" data-line-number="18">}</a>
<a class="sourceLine" id="cb373-19" data-line-number="19">mySampleDF<span class="op">$</span>SampleSize &lt;-<span class="st"> </span><span class="kw">as.factor</span>(mySampleDF<span class="op">$</span>SampleSize) <span class="co"># It&#39;s helpful to have these as a factor</span></a>
<a class="sourceLine" id="cb373-20" data-line-number="20"></a>
<a class="sourceLine" id="cb373-21" data-line-number="21"><span class="kw">ggplot</span>(<span class="dt">data =</span> mySampleDF) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb373-22" data-line-number="22"><span class="st">  </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">x =</span> SampleObservations, <span class="dt">color =</span> SampleSize)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb373-23" data-line-number="23"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">1</span><span class="op">/</span><span class="dv">2</span>, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">color =</span> <span class="st">&#39;black&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb373-24" data-line-number="24"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span>SampleSize) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb373-25" data-line-number="25"><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;Sample Mean&#39;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&#39;Density&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb373-26" data-line-number="26"><span class="st">  </span><span class="kw">ggtitle</span>(<span class="st">&#39;Sampling Distribution of the Mean of</span><span class="ch">\n</span><span class="st">the Exponential Distribution with Lambda = 2</span><span class="ch">\n</span><span class="st">for Varying Sample Sizes&#39;</span>)</a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-34-2.png" width="672" /></p>
<p>Note how the above plots become more normal as the sample size increases and their mean converges on the population mean.</p>
</div>
</div>
</div>
<div id="statistical-concepts---problem-set" class="section level3">
<h3><span class="header-section-number">3.3.3</span> Statistical Concepts - Problem Set</h3>
<p>No problem set for this section. If you desire:</p>
<ul>
<li>Prove the central limit theorem. Here are some solutions from <a href = "http://mathworld.wolfram.com/CentralLimitTheorem.html">Math World </a>.</li>
<li>Prove that the sample mean is an unbiased estimator of the population mean.</li>
</ul>
</div>
</div>
<div id="statistical-inference" class="section level2">
<h2><span class="header-section-number">3.4</span> Statistical Inference</h2>
<div id="statistical-inference---description" class="section level3">
<h3><span class="header-section-number">3.4.1</span> Statistical Inference - Description</h3>
<p>Statistical inference is a large field focused on the desire to describe the properties of a population from a sample such as the population distribution and associated parameters. There are different types of inference with different underlying philosophies and assumptions (e.g., parametric vs. non-parametric, frequentist vs. Bayesian). We do not claim to, nor do we have the time to cover all (or even most) types of statistical inference in this section. We will only review the typical, foundational types of inference seen in any general statistics course and/or as required for our specific analysis.</p>
</div>
<div id="statistical-inference---tutorial" class="section level3">
<h3><span class="header-section-number">3.4.2</span> Statistical Inference - Tutorial</h3>
<div id="confidence-intervals" class="section level4">
<h4><span class="header-section-number">3.4.2.1</span> Confidence Intervals</h4>
<p>In this section, we review standard confidence intervals. Since they are so commonly taught and used and because we will not make great use of them in this course, this section will be highly terse. For a reasonable treatment, please see the resources at <a href='https://www.khanacademy.org/math/ap-statistics/estimating-confidence-ap'>Khan Academy</a> or your other preferred statistics resource.</p>
<div id="what-is-a-confidence-interval" class="section level5">
<h5><span class="header-section-number">3.4.2.1.1</span> What is a Confidence Interval?</h5>
<p>A confidence interval is a range for an estimate of an unknown parameter of a distribution and an associated plausibility that the unknown parameter falls in that range. For example, we can estimate the mean of a distribution and develop a number of confidence intervals to estimate the mean and picture it as seen below:</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb374-1" data-line-number="1"><span class="co"># First, let&#39;s choose a known population - the standard normal distribution N(0, 1)</span></a>
<a class="sourceLine" id="cb374-2" data-line-number="2"><span class="co"># The pdf of N(0,1) is well known</span></a>
<a class="sourceLine" id="cb374-3" data-line-number="3">x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">-4</span>, <span class="dt">to =</span> <span class="dv">4</span>, <span class="dt">by =</span> <span class="fl">.01</span>)</a>
<a class="sourceLine" id="cb374-4" data-line-number="4">prob.x &lt;-<span class="st"> </span>(<span class="dv">1</span><span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">2</span><span class="op">*</span>pi))<span class="op">*</span><span class="kw">exp</span>(<span class="op">-</span>.<span class="dv">5</span><span class="op">*</span>(x<span class="op">^</span><span class="dv">2</span>))</a>
<a class="sourceLine" id="cb374-5" data-line-number="5"><span class="co"># We can see what this looks like.  We&#39;ll plot the mean as a red vertical line</span></a>
<a class="sourceLine" id="cb374-6" data-line-number="6"><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> prob.x)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">0</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>)</a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-35-1.png" width="672" /></p>
<p>We know that for this distribution, the true (population) mean is 0 and the true (population) standard deviation is 1. We can sample from the distribution (using, <code>rnorm()</code>) and build confidence intervals. Note that in this example, we see that one of the confidence intervals does not contain the mean. (Note that the code is not shown as we’ll review how to calculate the interval in the next section).</p>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
</div>
<div id="how-do-i-calculate-a-confidence-interval" class="section level5">
<h5><span class="header-section-number">3.4.2.1.2</span> How do I calculate a Confidence Interval?</h5>
<p>As previously stated, a confidence interval is a range of values that are thought to contain the true population parameter with some level of plausibility. If our parameter is <span class="math inline">\(\theta\)</span>, we want to find a lower, <span class="math inline">\(L\)</span>, and an upper, <span class="math inline">\(U\)</span>, bound such that the following statement is true:</p>
<p><span class="math inline">\(P(L &lt;= \theta &lt;= U) = 1 - \alpha\)</span></p>
<p>Where <span class="math inline">\(\alpha\)</span> is a generally small percentage, often 1, 5, or 10 percent such that we can have 99, 95, or 90 percent confidence respectively.</p>
<p>We can see this graphically if, for example, our parameter <span class="math inline">\(\theta\)</span> can be described by the standard normal distribution and we want 95% confidence that theta is between an upper and lower bound:</p>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<p>If we know, or can reasonably assume, the distribution for our parameter of interest, <span class="math inline">\(\theta\)</span> we can then solve for this explicitly. Often times, we can assume that our population is <em>approximately</em> normally distributed; if that is the case we can use the T-Distribution with an appropriate number of degrees of freedom.</p>
<!--
Fortunately for us, recall the *Central Limit Theorem* that tells us for a sufficiently large sample size, our sampling distribution (i.e., the distribution of the estimate of the parameter) tends toward the normal distribution for as the sample size tends toward infinity (assuming the variance is finite).  For smaller sizes, we typically use the T-Distribution with an appropriate number of degrees of freedom.
-->
<p>For further, detailed treatment of how confidence intervals work, see, e.g., <a href = 'https://www.youtube.com/playlist?list=PLdxWrq0zBgPXeOw0XI6c5TIRjbzEoHUE2'>Confidence Intervals Using Normality</a> or <a href = 'https://www.youtube.com/playlist?list=PLdxWrq0zBgPXA5gIL7DJBki6lHs70-jzc'>Confidence Intervals Using the T-Distribution</a>. As a side note, <a href = 'https://www.youtube.com/channel/UCjknLK_siVSCY14qfDu-f-w'>this channel (“Professor Knudson”)</a> seems to have pretty useful videos.</p>
<p>Finally, there are a number of standard (i.e., pre-solved) equations for confidence intervals of various parameters. You can generally find them in any statistics book, though <a href = 'http://www.mathcs.duq.edu/larget/math225/equations2.pdf'>here is a handy reference from Duquesne</a>.</p>
</div>
</div>
<div id="hypothesis-tests" class="section level4">
<h4><span class="header-section-number">3.4.2.2</span> Hypothesis Tests</h4>
<div id="what-is-a-hypothesis-test" class="section level5">
<h5><span class="header-section-number">3.4.2.2.1</span> What is a Hypothesis Test?</h5>
<p>A hypothesis test is a statistical means of stating whether or not it is plausible that a claim is true. These claims are typically questions like:</p>
<ul>
<li>It is likely that these two samples have the same parameter (e.g., the mean, mode, etc.).</li>
<li>It is likely that this data came from a certain type of distribution (e.g., this data is normally distributed).</li>
</ul>
<p>Answering a hypothesis test is one of the ways we can say a result is “statistically significant.” <strong>Having a solid, foundational understanding of hypothesis testing is requisite for understanding all of our future analysis.</strong> It comes up, in various forms, in all of our analysis including ANOVA and regression.</p>
<p>Understanding how hypothesis testing works in general is most important, followed by understanding specific hypothesis tests. Khan Academy has a good overview of hypothesis testing across three sets of videos:</p>
<ul>
<li><a href = "https://www.khanacademy.org/math/ap-statistics/tests-significance-ap">Khan Academy Significance Tests (Hypothesis Testing)</a>.</li>
<li><a href = "https://www.khanacademy.org/math/ap-statistics/two-sample-inference">Khan Academy Inference Comparing Two Groups or Populations</a>.</li>
<li><a href = "https://www.khanacademy.org/math/ap-statistics/chi-square-tests">Khan Academy Chi-Square Tests for Categorical Data</a>.</li>
</ul>
</div>
<div id="hypothesis-test-standard-operating-procedure-sop" class="section level5">
<h5><span class="header-section-number">3.4.2.2.2</span> Hypothesis Test “Standard Operating Procedure” (SOP)</h5>
<p>In the text, <em>Applied Statistics and Probability for Engineers</em> by Montgomery and Runger, the authors provide a seven step SOP for hypothesis testing:</p>
<ol style="list-style-type: decimal">
<li>Identify the parameter of interest.</li>
<li>State the null hypothesis.</li>
<li>State the alternative hypothesis.</li>
<li>Give the formula for the test statistic (based upon the assumptions).</li>
<li>State the rejection region for the selected significance level (i.e., find the critical value(s)).</li>
<li>Compute the test statistic.</li>
<li>Draw conclusions.
<ul>
<li>Decide to reject or fail to reject <span class="math inline">\(H_0\)</span>.</li>
<li>State conclusion in the appropriate problem context.</li>
</ul></li>
</ol>
<p>The first step, “Identify the parameter of interest,” is most important. As with any study, clearly defining your question is vital, because if you answer the wrong question perfectly, you still have a wrong answer. Along with identifying the parameter of interest, an analyst should also identify the reasonable assumptions he or she is willing to make to answer this question.</p>
<p>The second and third steps, “Identify the null and alternative hypothesis” are merely formalizing the question. These are typically formulated as:</p>
<p><span class="math inline">\(H_0: Claim\)</span></p>
<p><span class="math inline">\(H_A: Opposite\)</span></p>
<p>Where <span class="math inline">\(H_0\)</span> (sometimes listed as <span class="math inline">\(H_1\)</span>) is the “null hypothesis”. This is the hypothesis that you believe to be true and, if your hypothesis test results in a <em>plausible</em> value, it is the claim you will say is likely true. <span class="math inline">\(H_A\)</span> is the “alternative hypothesis” which is what you are claiming is likely true if you come up with a highly unlikely value for your test. It is typically framed as the inverse of <span class="math inline">\(H_0\)</span>.</p>
<p>The fourth step involves choosing the appropriate “test statistic.” In many (perhaps most) cases, statisticians have developed these statistics along with the appropriately identified assumptions and the analyst merely needs to choose the most appropriate test for his or her purposes. <strong>This choice, particularly, the assumptions you are making about this is significant.</strong></p>
<p>The fifth and sixth steps involve identifying, <em>a priori</em>, what the significance level is (e.g., 95%, 99%, etc.), then calculating the “rejection region” and then calculating the statistic, and seeing if the result falls in or out of the rejection region.</p>
<p>Finally, the analyst draws the appropriate conclusions based on the results of the tests. A few things to consider:</p>
<ul>
<li>It is not good statistical practice, assuming you set up the test appropriately, to adjust your critical values (i.e. your level) because you do not <em>like</em> your results. Similarly, one should not re-sample data to do the same test repeatedly. This so called “p-hacking” puts you at risk of eventually finding a false-positive or false-negative that will tell you what you want if you ignore all of the error you’ve introduced by doing the same test repeatedly.</li>
<li>The p-value (i.e., the probability that your observed statistic falls in the distribution of interest) does not come with varying levels of significance. Significance is stated up front (i.e., testing for a 90% significance, and then is binary - your results are significant or not).</li>
<li>Do not confuse statistical significance with practical significance. For example, consider two machines that produce widgets. You have identified that the mean weight of the widgets produced by the two machines is different by .01g to the 99.9% significance level. This <em>is</em> a statistically significant result, for sure, but the difference of .01g likely makes no <em>practical</em> difference if these widgets are used for all but the most precise machines.</li>
<li>Finally, recall that we are either <em>rejecting</em> or <em>failing to reject</em> the null hypothesis. When we reject the null hypothesis, we are saying it is unlikely</li>
</ul>
</div>
<div id="example-hypothesis-test-using-r" class="section level5">
<h5><span class="header-section-number">3.4.2.2.3</span> Example Hypothesis Test Using <em>R</em></h5>
<p>All of the above information has thus far (unfortunately) been largely theoretical. Let’s look at an example where we compare the mean of two samples of a population to see if they have the same mean. We will use the built in <em>R</em> data set, <code>iris</code>.</p>
<div class="sourceCode" id="cb375"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb375-1" data-line-number="1"><span class="co"># First, let&#39;s take two samples of size n from iris</span></a>
<a class="sourceLine" id="cb375-2" data-line-number="2">n &lt;-<span class="st"> </span><span class="dv">30</span></a>
<a class="sourceLine" id="cb375-3" data-line-number="3"></a>
<a class="sourceLine" id="cb375-4" data-line-number="4"><span class="co"># the dplyr function sample_n is a nice function that samples n rows of a data frame.  </span></a>
<a class="sourceLine" id="cb375-5" data-line-number="5"><span class="co"># We have opted to replace (i.e., you can select the same row more than once)</span></a>
<a class="sourceLine" id="cb375-6" data-line-number="6"></a>
<a class="sourceLine" id="cb375-7" data-line-number="7"><span class="kw">set.seed</span>(<span class="dv">212</span>) <span class="co"># Setting the seed is not good practice in general, but for consistency of</span></a>
<a class="sourceLine" id="cb375-8" data-line-number="8"><span class="co"># production and pedagogical purposes, we&#39;re setting it here</span></a>
<a class="sourceLine" id="cb375-9" data-line-number="9">sample<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">sample_n</span>(iris, n, <span class="dt">replace =</span> T)</a>
<a class="sourceLine" id="cb375-10" data-line-number="10"><span class="kw">set.seed</span>(<span class="dv">112</span>)</a>
<a class="sourceLine" id="cb375-11" data-line-number="11">sample<span class="fl">.2</span> &lt;-<span class="st"> </span><span class="kw">sample_n</span>(iris, n, <span class="dt">replace =</span> T)</a>
<a class="sourceLine" id="cb375-12" data-line-number="12"><span class="co"># For convenience, we&#39;ll only look at the vector of the associated sepal lengths</span></a>
<a class="sourceLine" id="cb375-13" data-line-number="13">sample<span class="fl">.1</span> &lt;-<span class="st"> </span>sample<span class="fl">.1</span><span class="op">$</span>Sepal.Length</a>
<a class="sourceLine" id="cb375-14" data-line-number="14">sample<span class="fl">.2</span> &lt;-<span class="st"> </span>sample<span class="fl">.2</span><span class="op">$</span>Sepal.Length</a>
<a class="sourceLine" id="cb375-15" data-line-number="15"></a>
<a class="sourceLine" id="cb375-16" data-line-number="16"><span class="co"># Let&#39;s visualize our data, we&#39;ll use green for sample 1 and blue for sample 2</span></a>
<a class="sourceLine" id="cb375-17" data-line-number="17"><span class="co"># The means are the solid lines</span></a>
<a class="sourceLine" id="cb375-18" data-line-number="18"><span class="co"># I like using density plots as they&#39;re a quick way to approximately visualize the distribution</span></a>
<a class="sourceLine" id="cb375-19" data-line-number="19"><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb375-20" data-line-number="20"><span class="st">  </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">x =</span> sample<span class="fl">.1</span>), <span class="dt">color =</span> <span class="st">&#39;green&#39;</span>, <span class="dt">fill =</span> <span class="st">&#39;green&#39;</span>, <span class="dt">alpha =</span> <span class="fl">.25</span>) <span class="op">+</span><span class="st"> </span><span class="co">#, binwidth = .2) + </span></a>
<a class="sourceLine" id="cb375-21" data-line-number="21"><span class="st">  </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(<span class="dt">x =</span> sample<span class="fl">.2</span>), <span class="dt">color =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">fill =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">alpha =</span> <span class="fl">.25</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb375-22" data-line-number="22"><span class="st">  </span><span class="kw">theme_minimal</span>() <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&#39;Sepal Length&#39;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&#39;Density&#39;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ggtitle</span>(<span class="st">&#39;Density Plot and Sample Means</span><span class="ch">\n</span><span class="st">Green is Sample 1</span><span class="ch">\n</span><span class="st">Blue is Sample 2&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb375-23" data-line-number="23"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(sample<span class="fl">.1</span>), <span class="dt">color =</span> <span class="st">&#39;green&#39;</span>, <span class="dt">size =</span> <span class="fl">1.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb375-24" data-line-number="24"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">mean</span>(sample<span class="fl">.2</span>), <span class="dt">color =</span> <span class="st">&#39;blue&#39;</span>, <span class="dt">size =</span> <span class="fl">1.5</span>) </a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-38-1.png" width="672" /></p>
<p>Clearly we know two things:</p>
<ol style="list-style-type: decimal">
<li>We sampled these from the same population.</li>
<li>Despite that, they produced somewhat different results in terms of the sample means and the distribution.</li>
</ol>
<p>The question for our hypothesis test is then, do these two samples “have the same mean”? i.e., do they come from the same population? We can therefore follow our hypothesis testing SOP.</p>
<p><strong>SOP Step 1:</strong> State the parameter of interest. In our case, the parameter of interest is the mean.</p>
<p><strong>SOP Step 2 &amp; 3:</strong> State the null and alternate hypotheses. In our case we can state these as:</p>
<p><span class="math inline">\(H_0: \mu_1 = \mu_2\)</span></p>
<p><span class="math inline">\(H_A: \mu_1 \neq \mu_2\)</span></p>
<p>Where <span class="math inline">\(\mu_i\)</span> is the mean of the ith sample.</p>
<p><strong>SOP Step 4:</strong> Give the formula for the test statistic. In this case, we can refer to any standard statistics text and identify the appropriate test statistic. In our case, we know that we have a sample size of <code>n = 30</code>, and we do not know the variance of our underlying population or even its distribution. However, our sample distributions are <em>approximately</em> normal (as we see from the plot above), and it is commonly accepted that the T-Test is appropriate for samples from approximately normal distributions as long as the sample size of ~30 or more. We’ll therefore use the T-Test.</p>
<p>The T-Test has the following statistic (note, you can read more about this test on the <a href = "https://www.itl.nist.gov/div898/handbook/eda/section3/eda353.htm#:~:text=">NIST Engineering Statistics Handbook</a>):</p>
<p><span class="math inline">\(T = \frac{\bar{x_1} - \bar{x_2}}{\sqrt{s_1^2/N_1 + s_2^2/N_2}}\)</span></p>
<p>Where <span class="math inline">\(\bar{x_i}\)</span> is the mean of the ith sample, <span class="math inline">\(s_i^2\)</span> is the sample variance of the ith sample, and <span class="math inline">\(N_i\)</span> is the ith sample size.</p>
<p><strong>SOP Step 5:</strong> State the chosen significance level and define the rejection region. Let’s assume our significance level is 95%. For convenience, we typically say this as the <span class="math inline">\(1-\alpha\)</span> level, so we have <span class="math inline">\(\alpha = .05\)</span>. What we are really saying is::</p>
<ol style="list-style-type: decimal">
<li>The distribution of our test statistic is the T distribution with the appropriate degrees of freedom for our sample size.</li>
<li>We will accept any test statistic that falls into the “middle 95%” of our distribution.</li>
<li>We will reject that our test statistic plausibly came from this distribution if the result is outside of this “middle 95%”.</li>
</ol>
<p>We can visualize this as follows:</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb376-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">-4</span>, <span class="dt">to =</span> <span class="dv">4</span>, <span class="dt">by =</span> <span class="fl">.01</span>)</a>
<a class="sourceLine" id="cb376-2" data-line-number="2"></a>
<a class="sourceLine" id="cb376-3" data-line-number="3"><span class="co"># First show the distribution</span></a>
<a class="sourceLine" id="cb376-4" data-line-number="4">myPlot &lt;-<span class="st"> </span><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb376-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> <span class="kw">dt</span>(x, (n<span class="op">*</span><span class="dv">2</span>) <span class="op">-</span><span class="st"> </span><span class="dv">2</span>))) <span class="op">+</span><span class="st"> </span><span class="co"># Plot the t distribution with 58 degrees of freedom</span></a>
<a class="sourceLine" id="cb376-6" data-line-number="6"><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&#39;X&#39;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">ylab</span>(<span class="st">&#39;Probability of X&#39;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">xlim</span>(<span class="kw">c</span>(<span class="op">-</span><span class="dv">5</span>, <span class="dv">5</span>))</a>
<a class="sourceLine" id="cb376-7" data-line-number="7"></a>
<a class="sourceLine" id="cb376-8" data-line-number="8">myPlot</a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-39-1.png" width="672" /></p>
<p>We can then identify the areas of this t-distribution where the probability of being above or below the number is 2.5% (as the distribution is symmetrical and we want to exclude <span class="math inline">\(\alpha = .05\)</span> from our plausible region).</p>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb377-1" data-line-number="1"><span class="co"># We can calculate the plausible region using the qt() function.  Recall from the</span></a>
<a class="sourceLine" id="cb377-2" data-line-number="2"><span class="co"># probability discussion that q[distro name] is the quantile for that distribution. </span></a>
<a class="sourceLine" id="cb377-3" data-line-number="3"><span class="co"># Please read about the qt() function with ?qt  </span></a>
<a class="sourceLine" id="cb377-4" data-line-number="4"></a>
<a class="sourceLine" id="cb377-5" data-line-number="5">lower.crit.value &lt;-<span class="st"> </span><span class="kw">qt</span>(.<span class="dv">025</span>, <span class="dv">58</span>)</a>
<a class="sourceLine" id="cb377-6" data-line-number="6">upper.crit.value &lt;-<span class="st"> </span><span class="kw">qt</span>(.<span class="dv">975</span>, <span class="dv">58</span>)</a>
<a class="sourceLine" id="cb377-7" data-line-number="7"></a>
<a class="sourceLine" id="cb377-8" data-line-number="8"><span class="co"># We can then plot these on our graph to show the regions where the test statistic might</span></a>
<a class="sourceLine" id="cb377-9" data-line-number="9"><span class="co"># fall and we would reject the null hypothesis</span></a>
<a class="sourceLine" id="cb377-10" data-line-number="10">myPlot <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb377-11" data-line-number="11"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> lower.crit.value, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb377-12" data-line-number="12"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> upper.crit.value, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb377-13" data-line-number="13"><span class="st">  </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="kw">seq</span>(<span class="op">-</span><span class="dv">4</span>,lower.crit.value, <span class="dt">by =</span> <span class="fl">.01</span>), <span class="kw">dt</span>(<span class="kw">seq</span>(<span class="op">-</span><span class="dv">4</span>,lower.crit.value, <span class="dt">by =</span> <span class="fl">.01</span>), <span class="dv">38</span>)), <span class="dt">fill =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">alpha =</span> <span class="fl">.25</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb377-14" data-line-number="14"><span class="st">  </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="kw">seq</span>(upper.crit.value,<span class="dv">4</span>, <span class="dt">by =</span> <span class="fl">.01</span>), <span class="kw">dt</span>(<span class="kw">seq</span>(upper.crit.value,<span class="dv">4</span>, <span class="dt">by =</span> <span class="fl">.01</span>), <span class="dv">38</span>)), <span class="dt">fill =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">alpha =</span> <span class="fl">.25</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb377-15" data-line-number="15"><span class="st">  </span><span class="kw">geom_label</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="dv">3</span>, <span class="dt">y =</span> <span class="fl">.3</span>, <span class="dt">label =</span> <span class="st">&#39;Upper Critical Region</span><span class="ch">\n</span><span class="st">If our Test Statistic falls in here,</span><span class="ch">\n</span><span class="st">we reject the null.&#39;</span>)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb377-16" data-line-number="16"><span class="st">  </span><span class="kw">geom_label</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="dv">-3</span>, <span class="dt">y =</span> <span class="fl">.3</span>, <span class="dt">label =</span> <span class="st">&#39;Lower Critical Region</span><span class="ch">\n</span><span class="st">If our Test Statistic falls in here,</span><span class="ch">\n</span><span class="st">we reject the null.&#39;</span>)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb377-17" data-line-number="17"><span class="st">  </span><span class="kw">geom_label</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="dv">0</span>, <span class="dt">y =</span> <span class="fl">.15</span>, <span class="dt">label =</span> <span class="st">&#39;Plausible Region</span><span class="ch">\n</span><span class="st">If our Test Statistic falls in here,</span><span class="ch">\n</span><span class="st">we fail to reject the null.&#39;</span>)) </a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<p><strong>SOP Step 6:</strong> Calculate the test statistic.
We can solve for this using the following <em>R</em> code:</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb378-1" data-line-number="1">T.value &lt;-<span class="st"> </span>(<span class="kw">mean</span>(sample<span class="fl">.1</span>) <span class="op">-</span><span class="st"> </span><span class="kw">mean</span>(sample<span class="fl">.2</span>))<span class="op">/</span>(((<span class="kw">sd</span>(sample<span class="fl">.1</span>)<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span><span class="dv">20</span>)<span class="op">+</span>((<span class="kw">sd</span>(sample<span class="fl">.2</span>)<span class="op">^</span><span class="dv">2</span>)<span class="op">/</span><span class="dv">20</span>))<span class="op">^</span>.<span class="dv">5</span></a>
<a class="sourceLine" id="cb378-2" data-line-number="2">T.value</a></code></pre></div>
<pre><code>## [1] 0.835691</code></pre>
<p><strong>SOP Step 7:</strong></p>
<p>As we calculated our test statistic to be 0.836, we see it falls squarely in the “plausible region.” We can see that here:</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb380-1" data-line-number="1">myPlot <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb380-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> lower.crit.value, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb380-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> upper.crit.value, <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb380-4" data-line-number="4"><span class="st">  </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="kw">seq</span>(<span class="op">-</span><span class="dv">4</span>,lower.crit.value, <span class="dt">by =</span> <span class="fl">.01</span>), <span class="kw">dt</span>(<span class="kw">seq</span>(<span class="op">-</span><span class="dv">4</span>,lower.crit.value, <span class="dt">by =</span> <span class="fl">.01</span>), <span class="dv">38</span>)), <span class="dt">fill =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">alpha =</span> <span class="fl">.25</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb380-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_area</span>(<span class="kw">aes</span>(<span class="kw">seq</span>(upper.crit.value,<span class="dv">4</span>, <span class="dt">by =</span> <span class="fl">.01</span>), <span class="kw">dt</span>(<span class="kw">seq</span>(upper.crit.value,<span class="dv">4</span>, <span class="dt">by =</span> <span class="fl">.01</span>), <span class="dv">38</span>)), <span class="dt">fill =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">alpha =</span> <span class="fl">.25</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb380-6" data-line-number="6"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> T.value, <span class="dt">color =</span> <span class="st">&#39;blue&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb380-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_label</span>(<span class="kw">aes</span>(<span class="dt">x =</span> T.value, <span class="dt">y =</span> <span class="fl">.3</span>, <span class="dt">label =</span> <span class="st">&#39;Observed Value&#39;</span>))</a></code></pre></div>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>As we see, we observed a value squarely in the “plausible region”. It is, therefore highly likely (95% level) that these two samples have the same mean. Of course, we already knew this since we drew are samples from the same population!</p>
</div>
<div id="that-was-annoying-cant-r-make-my-life-easier" class="section level5">
<h5><span class="header-section-number">3.4.2.2.4</span> That Was Annoying, Can’t <em>R</em> Make my Life Easier</h5>
<p>Of course, that was a lot of work just to get to the right critical values and test statistic. <em>R</em> has many built in functions that allow us to do this same sort of analysis. In our case, the <code>t.test()</code> function is what we want. We just have to set up our data slightly differently:</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb381-1" data-line-number="1"><span class="co"># t.test requires data to be set up in a manner that looks something like this:</span></a>
<a class="sourceLine" id="cb381-2" data-line-number="2">myDF &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">sepal.length =</span> <span class="kw">c</span>(sample<span class="fl">.1</span>, sample<span class="fl">.2</span>), <span class="dt">sample.number =</span> <span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&#39;Sample 1&#39;</span>, n), <span class="kw">rep</span>(<span class="st">&#39;Sample 2&#39;</span>, n)))</a>
<a class="sourceLine" id="cb381-3" data-line-number="3"><span class="kw">head</span>(myDF)</a></code></pre></div>
<pre><code>##   sepal.length sample.number
## 1          6.1      Sample 1
## 2          7.0      Sample 1
## 3          5.7      Sample 1
## 4          6.1      Sample 1
## 5          5.5      Sample 1
## 6          5.0      Sample 1</code></pre>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb383-1" data-line-number="1"><span class="co"># We then run the test </span></a>
<a class="sourceLine" id="cb383-2" data-line-number="2"><span class="kw">t.test</span>(sepal.length <span class="op">~</span><span class="st"> </span>sample.number, <span class="dt">data =</span> myDF)</a></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  sepal.length by sample.number
## t = 1.0235, df = 57.983, p-value = 0.3103
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.1879648  0.5812982
## sample estimates:
## mean in group Sample 1 mean in group Sample 2 
##               5.920000               5.723333</code></pre>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb385-1" data-line-number="1"><span class="co"># We can also store the results:</span></a>
<a class="sourceLine" id="cb385-2" data-line-number="2">myT.Test &lt;-<span class="st"> </span><span class="kw">t.test</span>(sepal.length <span class="op">~</span><span class="st"> </span>sample.number, <span class="dt">data =</span> myDF)</a></code></pre></div>
<p>This gives us a nice summary of the test. You’ll note a few things:</p>
<ol style="list-style-type: decimal">
<li>We get the same test statistic result. Our hand result was: t = 0.835691 and the t.test() was t = 1.0235083.</li>
<li>The <code>t.test()</code> function had a slightly more accurate assessment of degrees of freedom of 57.983 vs. my estimate of 58. We could have calculated the degrees of freedom more exactly manually (see the calculation in the NIST handbook link above), but the rough estimate was sufficiently good.</li>
<li>The <code>t.test()</code> gives us the alternative hypothesis, the confidence interval, the p-value, etc… all rather conveniently.</li>
</ol>
<p>Finally, if you look at the documentation for <code>t.test()</code> you’ll see you have a number of options, e.g., what your alternative is, what the difference between the two means is (equality implies the difference is 0, sometimes you may want some different distinction, etc.).</p>
</div>
<div id="standard-tests-in-r" class="section level5">
<h5><span class="header-section-number">3.4.2.2.5</span> Standard Tests in <em>R</em></h5>
<p><em>R</em> has a number of very useful tests pre-built in. Here are a few:</p>
<ul>
<li><code>t.test()</code>:
<ul>
<li>Description: This function allows one to do the standard T-Test of the mean. It has options to do one or two sided, paired or not, equal or unequal variance.<br />
</li>
<li>Assumptions: The T-Test assumes one’s sample(s) are independent, identically distributed, and come from a normal distribution. That stated, the T-Test is generally accepted for data where we know the population is not normally distributed so long as we: 1) have “approximately normal” conditions and 2) have a sufficiently large sample size (generally ~N = 30).</li>
</ul></li>
<li><code>prop.test()</code>:
<ul>
<li>Description: This function considers the Pearson’s Chi Squared test as a proportion test. It is slightly more onerous to do this by hand than the large sample proportion test commonly taught in most statistics classes, but it’s a bit more powerful! Also, it’s not onerous in <em>R</em>. It has options for being a one or two sided test and various ways to input data. It also has the option to use “Yate’s Continuity Correction”, which is a way of correcting for bias introduced by small samples.<br />
</li>
<li>Assumptions: It assumes that the samples are independent and identically distributed. A general rule of thumb is that one should have at least five observations for each of the proportions (i.e., one cannot have too small of a count).<br />
</li>
</ul></li>
<li><code>chisq.test()</code>:
<ul>
<li>Description: This test does a standard chi squared test for goodness of fit. It is very similar to <code>prop.test</code> though used in a slightly different manner. Look closely at the documentation to see the differences.</li>
<li>Assumptions: These are the same as prop.test.</li>
</ul></li>
<li><code>binom.test()</code>:
<ul>
<li>Description: This is an “exact test” of a simple null hypothesis about the probability of success in a Bernoulli experiment (recall, a Bernoulli trial is an experiment where one can only have a success with probability p or failure with probability 1-p). One provides the number of success <code>x</code>, the number of trials <code>n</code>, the probability <code>p</code>, and if one wants a one or two sided test.</li>
<li>Assumptions: This assumes that one is doing 1) Bernoulli trials, 2) they are independent of each other, and 3) they are from the same distribution (i.e., the p for each trial is consistent).<br />
</li>
</ul></li>
<li><code>shapiro.test()</code>:
<ul>
<li>Description: This function performs the Shapiro Wilk test of normality. It’s null hypothesis is that the data is normally distributed (it does not say anything about the mean or variance). A low p-value for this (e.g., &lt; 0.01) implies one should reject the null hypothesis and conclude the data is not normally distributed.</li>
<li>Assumptions: No significant assumptions.</li>
</ul></li>
</ul>
<p>There are many other built in tests, these are simply a few. As a reminder, before doing a test:</p>
<ol style="list-style-type: decimal">
<li>Ensure you understand the test itself: what the null and alternative hypotheses are; what assumptions are necessary to make the test valid; what the test is sensitive to.<br />
</li>
<li>Ensure you understand the function that is doing the test: read the documentation; format your data correctly; choose the appropriate parameters. I often find myself checking <em>R</em> functions with toy problems that I can calculate by hand to understand what is actually occurring in the test if I’m not familiar with it.</li>
</ol>
</div>
<div id="error" class="section level5">
<h5><span class="header-section-number">3.4.2.2.6</span> Error</h5>
<p>The above discussion of inference focuses on <em>plausibility</em> of some hypothesis or event as defined by the likelihood of seeing a result given a presumed distribution.</p>
<p>For example, presume we have an absolutely fair coin. If we flip the coin ten times, we can count the proportion of heads and do a hypothesis test to assess if it is plausible that this coin is truly fair. In general, we’ll likely see about five heads, though it would not be unexpected to see 3, 4, 5, 6, or 7. That stated, we would certainly start questioning the fairness of the coin if we observed 10 heads. It <em>is</em> a possible outcome of flipping a fair coin 10 times, but a highly unlikely one (1 in 1024) and we would almost certainly reject the null hypothesis (erroneously) that the coin is fair. We call this an <em>error</em>.</p>
<p>More specifically, there are four possible states of the world based on absolute truth of <span class="math inline">\(H_0\)</span> and the decision based on the hypothesis test. Two of the states result in no error and the other two result in an error. We can see this as:</p>
<ul>
<li><span class="math inline">\(H_0\)</span> is true and we fail to reject <span class="math inline">\(H_0\)</span>: No error.</li>
<li><span class="math inline">\(H_0\)</span> is true and we reject <span class="math inline">\(H_0\)</span>: <font color = 'red'>Type I Error</font></li>
<li><span class="math inline">\(H_0\)</span> is false and we fail to reject <span class="math inline">\(H_0\)</span>: <font color = 'red'>Type II Error</font></li>
<li><span class="math inline">\(H_0\)</span> is false and reject <span class="math inline">\(H_0\)</span>: No error.</li>
</ul>
<p>If you recall from our discussion of hypothesis testing, we had a <span class="math inline">\(1 - \alpha\)</span> level of significance. The <span class="math inline">\(\alpha\)</span> is specifically the probability of making a Type I error. The probability of making a Type II Error is generally termed as <span class="math inline">\(\beta\)</span> and the power of a test is known as the power of the test.</p>
<p><strong>There is an intrinsic and unavoidable trade-off between the significance of a test and the power of a test.</strong> The specific trade that an analyst makes in this trade-off is not of general importance; what is important is that the analyst understands the trade and makes a decision that is appropriate and acceptable for the problem at hand.</p>
<p>We can visualize this error as follows:</p>
<p><img src="03-Statistics_Review_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>In the above figure we can really see what is occurring with a hypothesis test. First, note that our null hypothesis (depicted as the curve in black) is really asking us whether or not our observed value likely comes from a distribution (as we identified by our test statistic). Second, we see that in reality our sample comes from some population described by a probability distribution (shown as the curve in green). Ideally, this distribution is either closely aligned with our hypothesis so that we can fail to reject or very distinct from our hypothesis so that we can correctly reject the null. We see our critical value as the vertical blue line. We choose to reject or fail to reject the null hypothesis based on where our observation falls on the X axis. If it is to the “left” of the critical value, we fail to reject. If it so happens that our true alternative is not aligned with our null hypothesis, we may still observe a value that causes us to fail to reject and get a Type II error. Conversely, if our true alternative is the same as the null hypothesis (not depicted), we may observe an unlikely X value and reject anyway as seen in the Type I error. You can see then, that as you vary your critical value you are trading Type I errors for Type II errors and Significance for Power.</p>
<!--  Not ready to show this - we'll cover it in a future iteration of the advanced topics section of the course.

#### Randomization Tests

This may not be a familiar topic, but it is highly powerful.  David Howell of the University of Vermont has a really useful overview <a href = "https://www.uvm.edu/~statdhtx/StatPages/Randomization%20Tests/RandomizationTestsOverview.html">here</a>.  His main page is <a href = "https://www.uvm.edu/~statdhtx/StatPages/">here</a>.

-->
</div>
</div>
</div>
<div id="statistical-inference---conclusion" class="section level3">
<h3><span class="header-section-number">3.4.3</span> Statistical Inference - Conclusion</h3>
<p>Statistical inference is an expansive field<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a>. This tutorial assumes some initial familiarity with hypothesis testing, and reviewed a few of the common methods and tests. At the end of the day, it is important to recall three things:</p>
<ol style="list-style-type: decimal">
<li>Understand what a statistical test is asking. It is asking if it is plausible to observe one’s sample given a set of conditions (i.e., one’s assumptions and the test one is doing). There is always an inherent possibility of error (both Type I and II).</li>
<li>Understand the conditions for a given test - what the parameters are, what the assumptions are, etc. This holds true for both the mathematics of it (i.e., what you would find in a text book) and the computational aspects of it (i.e., how one codes it in a computer).</li>
<li>If you don’t know a test, it is entirely worth researching it, working to understand it, and talking with others about it.</li>
</ol>
</div>
<div id="statistical-inference---problem-set" class="section level3">
<h3><span class="header-section-number">3.4.4</span> Statistical Inference - Problem Set</h3>
<ul>
<li>You can view the problem set here <a href = "/_Chapter3_ProblemSets/Chapter_2-3_Problem_Set_Questions.html"> Statistical Inference Problem Set </a>.</li>
<li>The problem set as an R Markdown is here for your convenience: <a href = "/_Chapter3_ProblemSets/Chapter_2-3_Problem_Set_Questions.Rmd"> Statistical Inference Problem Set </a>.</li>
<li>You can download the Ames Iowa data set here <a href = "/_Chapter3_ProblemSets/ames.csv"> Ames, Iowa Data Set </a>.</li>
<li>You can download the the sample simulation data <a href = '/_Chapter3_ProblemSets/Chap2_DataSet.csv'> here (Chap2_DataSet.csv)</a>.</li>
<li>You can view the problem set solution here <a href = "/_Chapter3_ProblemSets/Chapter_2-3_Problem_Set_Answers.html"> Here </a>.</li>
</ul>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>Added 7 April 2020<a href="statistics-review.html#fnref1" class="footnote-back">↩</a></p></li>
<li id="fn2"><p>One may say it is a minefield!<a href="statistics-review.html#fnref2" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="analysis-of-variance-anova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "chapter"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
